// Role: the audit grades for audit/sample-0_1.json. One record per sampled entry.
// Contract: exports GRADES = [{ id, sources: { key: url }, fields: { name, description, input, output,
//   preserved, broken: { verdict, src?, quote?, note? } } }]. verdict: confirmed, imprecise, wrong,
//   unsupported. Any verdict but unsupported needs src and a verbatim quote from that source; any verdict
//   but confirmed needs a note. Checked by scripts/audit.mjs; quotes checked live by --verify-quotes.
// Invariant: data only. Grades are claims about entries, never edits to them. A grade judges the entry's
//   claim; the quote is the evidence, and a note says when the evidence is indirect.
"use strict";

const C = (src, quote, note) => ({ verdict: "confirmed", src, quote, ...(note ? { note } : {}) });
const I = (src, quote, note) => ({ verdict: "imprecise", src, quote, note });
const X = (src, quote, note) => ({ verdict: "wrong", src, quote, note });
const U = (note) => ({ verdict: "unsupported", note });
const g = (id, sources, fields) => ({ id, sources, fields });
const W = (t) => `https://en.wikipedia.org/w/index.php?action=raw&title=${t}`;

const GRADES = [
  // D1: combinatorics and graph theory (landed)
  g("D1-045", { w: W("Graph_bandwidth"), p: W("Indifference_graph") }, {
    name: C("w", "a proper interval supergraph of the given graph"),
    description: I("w", "The bandwidth may also be defined as one less than the maximum clique size in a proper interval supergraph of the given graph, chosen to minimize its clique size", "Conflates two objectives: completion minimizes added edges, while the bandwidth link is to minimizing clique size. \"Stricter than interval completion\" is right (proper interval graphs are a subclass)."),
    input: C("w", "a proper interval supergraph of the given graph"),
    output: C("p", "these graphs are also called unit interval graphs or proper interval graphs; they form a subclass of the interval graphs"),
    preserved: C("w", "a proper interval supergraph of the given graph", "A supergraph keeps the vertices and edges."),
    broken: U("Vacuous: \"non-proper-interval structure\" restates the output type."),
  }),
  g("D1-110", { r: W("Reflection_(mathematics)") }, {
    name: C("r", "is a mapping from a Euclidean space to itself that is an isometry with a hyperplane as the set of fixed points"),
    description: C("r", "is a mapping from a Euclidean space to itself that is an isometry with a hyperplane as the set of fixed points"),
    input: C("r", "this set is called the axis (in dimension 2) or plane (in dimension 3) of reflection"),
    output: C("r", "The image of a figure by a reflection is its mirror image"),
    preserved: C("r", "is a mapping from a Euclidean space to itself that is an isometry"),
    broken: C("r", "every improper rotation is the result of reflecting in an odd number", "Indirect: orientation reversal follows from reflections generating the improper rotations."),
  }),
  g("D1-085", { a: "https://arxiv.org/abs/2402.01483" }, {
    name: C("a", "unify and simplify known bijections between rectangulations and permutation classes"),
    description: C("a", "unify and simplify known bijections between rectangulations and permutation classes"),
    input: C("a", "weak rectangulations that preserve rectangle-segment adjacencies"),
    output: C("a", "known bijections between rectangulations and permutation classes"),
    preserved: C("a", "weak rectangulations that preserve rectangle-segment adjacencies"),
    broken: U("Interpretive: \"geometric representation replaced by permutation\" is a gloss, not a stated property."),
  }),
  g("D1-111", { r: W("Rotation_(mathematics)") }, {
    name: C("r", "Any rotation is a motion of a certain space that preserves at least one point"),
    description: C("r", "Any rotation is a motion of a certain space that preserves at least one point"),
    input: C("r", "Any rotation is a motion of a certain space that preserves at least one point"),
    output: C("r", "Any rotation is a motion of a certain space that preserves at least one point"),
    preserved: C("r", "it leaves the distance between any two points unchanged after the transformation. But a (proper) rotation also has to preserve the orientation structure"),
    broken: C("r", "Any rotation is a motion of a certain space that preserves at least one point", "Positions of non-fixed points change by definition of a nontrivial motion."),
  }),
  g("D1-017", { o: W("Graph_operations") }, {
    name: C("o", "Graph with all the edges that connect the vertices of the first graph with the vertices of the second graph"),
    description: C("o", "Graph with all the edges that connect the vertices of the first graph with the vertices of the second graph"),
    input: C("o", "Graph with all the edges that connect the vertices of the first graph with the vertices of the second graph"),
    output: C("o", "Graph with all the edges that connect the vertices of the first graph with the vertices of the second graph"),
    preserved: C("o", "Graph with all the edges that connect the vertices of the first graph with the vertices of the second graph", "Each input graph is an induced subgraph of the join."),
    broken: U("\"Sparsity\" is a reasonable gloss; not stated by the source."),
  }),
  // D2: algebra and algebraic geometry (landed)
  g("D2-191", { l: W("Loewy_ring") }, {
    name: C("l", "If M is a module, then define the Loewy series", "The socle filtration is the Loewy (socle) series."),
    description: I("l", "If M is a module, then define the Loewy series", "Each layer is the socle of a quotient, which is semisimple, not simple: \"simple layers\" should be \"semisimple layers\"."),
    input: C("l", "If M is a module, then define the Loewy series"),
    output: C("l", "The Loewy length of M is defined to be the smallest"),
    preserved: I("l", "every non-zero left (right) module has a non-zero socle", "Semisimple, not simple, structure per layer."),
    broken: U("Vacuous: \"global structure\"."),
  }),
  g("D2-120", { f: W("Flip_(algebraic_geometry)") }, {
    name: C("f", "the flop of f if K is relatively trivial"),
    description: C("f", "the flop of f if K is relatively trivial", "\"Numerically trivial\" matches K relatively trivial on the contracted curves."),
    input: I("f", "In applications, f is often a small contraction of an extremal ray", "The contraction is K-trivial and small; \"trivial extremal contraction\" misstates it."),
    output: C("f", "flips and flops are codimension-2 surgery operations"),
    preserved: C("f", "any two birationally equivalent minimal models are connected by a sequence of flops", "Birational type (hence Kodaira dimension) is kept; the canonical class is kept in the sense that K stays trivial on the flopped curves."),
    broken: U("Plausible (the intersection form on the flopped locus changes) but not stated by the source."),
  }),
  g("D2-067", { s: W("Smith_normal_form") }, {
    name: C("s", "is a normal form that can be defined for any matrix (not necessarily square) with entries in a principal ideal domain"),
    description: C("s", "The Smith normal form of a matrix is diagonal, and can be obtained from the original matrix by multiplying on the left and right by invertible square matrices"),
    input: C("s", "with entries in a principal ideal domain"),
    output: C("s", "The Smith normal form of a matrix is diagonal"),
    preserved: C("s", "are called the elementary divisors, invariants, or invariant factors"),
    broken: U("Vacuous: \"original entries\"."),
  }),
  g("D2-075", { q: W("Field_of_fractions") }, {
    name: C("q", "the field of fractions of an integral domain is the smallest field in which it can be embedded"),
    description: C("q", "the field of fractions of an integral domain is the smallest field in which it can be embedded"),
    input: C("q", "the field of fractions of an integral domain is the smallest field in which it can be embedded"),
    output: C("q", "the field of fractions of an integral domain is the smallest field in which it can be embedded"),
    preserved: C("q", "the smallest field in which it can be embedded"),
    broken: C("q", "the smallest field in which it can be embedded", "In a field every nonzero element is invertible."),
  }),
  g("D2-200", { v: W("Invariant_theory") }, {
    name: C("v", "This space of invariant polynomials is denoted"),
    description: C("v", "the set of polynomials such that g\\cdot f = f for all g\\in G"),
    input: C("v", "With this action it is natural to consider the subspace of all polynomial functions which are invariant under this group action"),
    output: C("v", "If the ring of invariants is finitely generated"),
    preserved: C("v", "If the ring of invariants is finitely generated"),
    broken: C("v", "which are invariant under this group action", "Non-invariant elements are excluded by definition."),
  }),
  // D3: logic and proof theory (landed)
  g("D3-124", { p: W("Prenex_normal_form") }, {
    name: C("p", "these rules require that the variable quantified in one subformula does not appear free in the other subformula"),
    description: C("p", "these rules require that the variable quantified in one subformula does not appear free in the other subformula"),
    input: C("p", "these rules require that the variable quantified in one subformula does not appear free in the other subformula"),
    output: C("p", "Every formula in classical logic is logically equivalent to a formula in prenex normal form"),
    preserved: C("p", "Every formula in classical logic is logically equivalent to a formula in prenex normal form", "Classical logic; some shifts fail intuitionistically, which the entry does not say."),
    broken: U("Vacuous: \"original quantifier placement\"."),
  }),
  g("D3-002", { n: W("Natural_deduction") }, {
    name: C("n", "any derivation containing an introduction of a connective followed immediately by its elimination can be turned into an equivalent derivation without this detour"),
    description: I("n", "It is a check on the strength of elimination rules", "Normalization presupposes harmony (local reducibility); it does not guarantee it. The rest of the description is right."),
    input: C("n", "any derivation containing an introduction of a connective followed immediately by its elimination"),
    output: C("n", "In most logics, every derivation has an equivalent normal derivation, called a normal form"),
    preserved: I("n", "can be turned into an equivalent derivation without this detour", "Provability is preserved; \"logical harmony\" is a property of the rules, not something a normalization step preserves."),
    broken: U("Correct in fact (normal proofs can be far longer), but not stated by the source."),
  }),
  g("D3-117", { c: W("Conjunctive_normal_form"), s: W("Skolem_normal_form") }, {
    name: C("c", "This is the only step that preserves only satisfiability rather than equivalence"),
    description: C("c", "Move quantifiers outwards", "The source's conversion procedure runs prenexing, Skolemizing, dropping universals and distributing, as the entry says."),
    input: C("s", "Every first-order formula may be converted into Skolem normal form"),
    output: C("c", "Drop all universal quantifiers"),
    preserved: C("s", "is equisatisfiable with it: it is satisfiable if and only if the original one is satisfiable"),
    broken: C("s", "The resulting formula is not necessarily equivalent to the original one"),
  }),
  g("D3-068", { k: W("Core_model") }, {
    name: C("k", "In set theory, the core model is a definable inner model of the universe of all sets"),
    description: I("k", "Intuitively, the core model is \"the largest canonical inner model there is\"", "\"Maximal inner model not containing specific large cardinals\" is the right intuition, but the source stresses that the core model is not one object: it is a class of inner models, each defined relative to an anti-large-cardinal hypothesis. The consistency-strength claim is not stated."),
    input: C("k", "under the right set-theoretic assumptions have very special properties"),
    output: C("k", "it is a class of inner models"),
    preserved: C("k", "most notably covering properties"),
    broken: U("Not stated by the source."),
  }),
  g("D3-085", { l: W("Constructible_universe") }, {
    name: C("l", "This gives rise to the concept of relative constructibility, of which there are two flavors"),
    description: C("l", "This gives rise to the concept of relative constructibility, of which there are two flavors"),
    input: C("l", "includes or is influenced by a set that is not constructible"),
    output: C("l", "of which there are two flavors, denoted by L(A) and L[A]", "The entry names only L[B] and omits the L(B) flavor."),
    preserved: U("Vacuous: restates the relation."),
    broken: U("\"Computational boundedness\" has no evident meaning here; likely noise."),
  }),
  // D4: topology and geometric methods (landed)
  g("D4-414", { v: W("Vector_bundle") }, {
    name: C("v", "may be glued over the intersection"),
    description: C("v", "may be glued over the intersection"),
    input: C("v", "may be glued over the intersection"),
    output: C("v", "is called a local trivialization of the vector bundle"),
    preserved: C("v", "Vector bundles are almost always required to be locally trivial"),
    broken: C("v", "is called the trivial bundle of rank k over", "Global triviality is the special case; transition functions encode its failure."),
  }),
  g("D4-186", { h: W("Hough_transform") }, {
    name: C("h", "The purpose of the technique is to find imperfect instances of objects within a certain class of shapes by a voting procedure"),
    description: C("h", "This voting procedure is carried out in a parameter space"),
    input: C("h", "The classical Hough transform was concerned with the identification of lines in the image"),
    output: C("h", "from which object candidates are obtained as local maxima in a so-called accumulator space"),
    preserved: U("Vacuous: \"shape detection\" names the purpose, not an invariant."),
    broken: U("Vacuous: \"non-shape features\"."),
  }),
  g("D4-326", { r: W("Relative_homology") }, {
    name: C("r", "If we denote this quotient by"),
    description: C("r", "induces a boundary map"),
    input: C("r", "induces a boundary map"),
    output: C("r", "An application of the snake lemma then yields a long exact sequence"),
    preserved: C("r", "The excision theorem says that removing a sufficiently nice subset"),
    broken: C("r", "The connected component containing x_0 becomes trivial in relative homology", "Homology carried by A is quotiented out, as the entry says."),
  }),
  g("D4-091", { c: W("Cup_product") }, {
    name: C("c", "the cup product is a method of adjoining two cocycles of degree p and q to form a composite cocycle of degree p+q"),
    description: C("c", "turning the cohomology of a space X into a graded ring"),
    input: C("c", "adjoining two cocycles of degree p and q"),
    output: C("c", "to form a composite cocycle of degree p+q"),
    preserved: C("c", "This defines an associative (and distributive) graded commutative product operation in cohomology"),
    broken: U("Vacuous: \"individual class detail\"."),
  }),
  g("D4-431", { w: W("Wirtinger's_inequality_for_functions") }, {
    name: C("w", "the Wirtinger inequality is an important inequality for functio"),
    description: I("w", "It was used by Adolf Hurwitz in 1901 to give a new proof of the isoperimetric inequality for curves in the plane", "Wirtinger's inequality bounds a function by its derivative (a Poincare-type inequality); relating arc length to enclosed area is the isoperimetric inequality it is used to prove. The entry states the application as the inequality."),
    input: I("w", "Let {{mvar|y}} be a continuous and differentiable function", "The input is a function (periodic, or with zero boundary values or mean), not a closed curve."),
    output: I("w", "all of which can be viewed as certain forms of the Poincar", "The output is an integral bound between a function and its derivative; the isoperimetric bound is a consequence."),
    preserved: U("Vacuous."),
    broken: U("Vacuous."),
  }),
  // D5: probability and information theory (landed)
  g("D5-070", { i: W("Inverse_transform_sampling") }, {
    name: C("i", "Inverse transformation sampling takes uniform samples of a number u between 0 and 1"),
    description: C("i", "the random variable F_X^{-1}(U) has the same distribution as X"),
    input: C("i", "and U is uniform on [0,1]"),
    output: C("i", "the random variable F_X^{-1}(U) has the same distribution as X"),
    preserved: C("i", "has the same distribution as X"),
    broken: U("Vacuous: \"uniform source\"."),
  }),
  g("D5-054", { g: W("Girsanov_theorem") }, {
    name: C("g", "if Q is a measure being absolutely continuous with respect to P, then every P-semimartingale is also a Q-semimartingale"),
    description: C("g", "changes the asset's drift from"),
    input: C("g", "changes the asset's drift from"),
    output: C("g", "then every P-semimartingale is also a Q-semimartingale"),
    preserved: C("g", "while leaving the diffusion coefficient"),
    broken: C("g", "changes the asset's drift from"),
  }),
  g("D5-132", { k: "https://arxiv.org/abs/math/0202285" }, {
    name: C("k", "the foldings approach of John Stallings"),
    description: C("k", "the foldings approach of John Stallings", "Filed under probability and information theory; it belongs to combinatorial group theory."),
    input: I("k", "the foldings approach of John Stallings", "The input is a labeled graph (for a finitely generated subgroup of a free group); calling it an automaton is a reading, and the group-theoretic setting is not named."),
    output: C("k", "pursue a detailed study of the subgroup structure of free groups", "The folded core graph represents the subgroup."),
    preserved: U("Correct in fact (folding preserves the subgroup the graph represents), but the abstract does not state it."),
    broken: U("Vacuous: \"all redundancy\"."),
  }),
  g("D5-130", { a: W("Anscombe_transform") }, {
    name: C("a", "is a variance-stabilizing transformation that transforms a random variable with a Poisson distribution"),
    description: C("a", "is a variance-stabilizing transformation that transforms a random variable with a Poisson distribution", "The Anscombe transform is the shifted square root."),
    input: C("a", "a random variable with a Poisson distribution"),
    output: C("a", "into one with an approximately standard Gaussian dis"),
    preserved: C("a", "is a variance-stabilizing transformation"),
    broken: U("Vacuous: \"scale\"."),
  }),
  g("D5-015", { b: W("Box–Muller_transform") }, {
    name: C("b", "is a random number sampling method for generating pairs of independent, standard, normally distributed"),
    description: C("b", "is a random number sampling method for generating pairs of independent, standard, normally distributed"),
    input: C("b", "given a source of uniforml"),
    output: C("b", "generating pairs of independent, standard, normally distributed"),
    preserved: C("b", "generating pairs of independent, standard, normally distributed"),
    broken: U("Vacuous: \"uniform structure\"."),
  }),
  // D6: analysis and functional analysis (landed)
  g("D6-077", { i: W("Itô_calculus") }, {
    name: C("i", "which is a Brownian motion or, more generally, a semimartingale. The result of the integration is then another stochastic process"),
    description: C("i", "Typically, the left end of the interval is used", "The contrast with Stratonovich confirms the chain-rule claim."),
    input: C("i", "which is a Brownian motion or, more generally, a semimartingale"),
    output: C("i", "The result of the integration is then another stochastic process"),
    preserved: I("i", "The stochastic integral satisfies the It", "The isometry is right (for Brownian or L^2 martingale integrators). \"Martingale property\" overstates: against a local martingale the integral is a local martingale, and against a general semimartingale it is a semimartingale."),
    broken: C("i", "it does follow the chain rule, and does not require It", "Said of the Stratonovich integral, by contrast with Ito's."),
  }),
  g("D6-014", { b: W("Borel_functional_calculus") }, {
    name: C("b", "the bounded Borel functional calculus of a self adjoint operator T on Hilbert s"),
    description: C("b", "Extending by continuity defines f(T) for a continuous function f", "The source develops the self-adjoint case; the normal case the entry names is the standard generalization."),
    input: C("b", "the bounded Borel functional calculus of a self adjoint operator T on Hilbert s", "Self-adjoint in the source; normal in the entry."),
    output: C("b", "is an involution-preserving and unit-preserving homomorphism from the ring of complex-valued bounded measurable functions"),
    preserved: C("b", "is an involution-preserving and unit-preserving homomorphism"),
    broken: U("Vacuous: non-measurable functions are outside the domain, not broken by the map."),
  }),
  g("D6-117", { l: W("Lebesgue's_decomposition_theorem") }, {
    name: I("l", "is absolutely continuous with respect to", "The decomposition into absolutely continuous and singular parts is Lebesgue's decomposition; Radon-Nikodym then gives the density of the first part. The name conflates the two theorems, though the content is right."),
    description: C("l", "is absolutely continuous with respect to"),
    input: C("l", "is absolutely continuous with respect to"),
    output: C("l", "are singular"),
    preserved: C("l", "is absolutely continuous with respect to"),
    broken: U("Vacuous: \"unified measure description\"."),
  }),
  g("D6-060", { h: W("Hadamard_transform") }, {
    name: C("h", "is an example of a generalized class of Fourier transforms"),
    description: C("h", "also known as the Walsh"),
    input: C("h", "is an example of a generalized class of Fourier transforms"),
    output: C("h", "It performs an orthogonal, symmetric, involutive, linear operat"),
    preserved: C("h", "It performs an orthogonal, symmetric, involutive, linear operat", "Orthogonal gives Parseval; involutive gives self-inverse."),
    broken: U("\"Complex phase information\": the transform is real, so there is no phase to break; not stated by the source."),
  }),
  g("D6-062", { k: W("Hankel_transform") }, {
    name: C("k", "is the Bessel function of the first kind of order"),
    description: C("k", "then its two-dimensional Fourier transform is given by", "The link to the 2D Fourier transform of circularly symmetric functions is stated; diagonalizing the radial Laplacian is not."),
    input: C("k", "is expanded in a multipole series"),
    output: C("k", "The inverse Hankel transform of"),
    preserved: C("k", "the Hankel transform defined this way is also its own inverse"),
    broken: U("Vacuous: \"Cartesian structure\"."),
  }),
  // D8: computational and algorithmic methods (landed)
  g("D8-034", { c: W("CUR_matrix_approximation") }, {
    name: C("c", "A CUR matrix approximation is a set of three matrices C, U and R that, when multiplied together, closely approximate a given matrix"),
    description: C("c", "the rows and columns come from the original matrix"),
    input: C("c", "closely approximate a given matrix"),
    output: C("c", "A CUR matrix approximation is a set of three matrices C, U and R"),
    preserved: C("c", "the rows and columns come from the original matrix (rather than left and right singular vectors)"),
    broken: C("c", "less accurate than the SVD"),
  }),
  g("D8-133", { s: W("Square_root_of_a_matrix") }, {
    name: X("s", "Matrix B such that B", "The name is the matrix square root; the content describes marching triangles (isosurface reconstruction). Name and content are misaligned."),
    description: X("s", "Matrix B such that B", "Describes marching triangles, not a matrix square root."),
    input: X("s", "Matrix B such that B", "Cross-sectional data and an isovalue; a matrix square root takes a square matrix."),
    output: X("s", "Matrix B such that B", "A triangle mesh; a matrix square root returns a matrix B."),
    preserved: X("s", "Matrix B such that B", "Surface topology belongs to the misplaced content."),
    broken: X("s", "Matrix B such that B", "Belongs to the misplaced content."),
  }),
  g("D8-083", { t: "https://arxiv.org/abs/1011.1595" }, {
    name: C("t", "a structured dimension-reduction map called the subsampled randomized Hadamard transform"),
    description: C("t", "a structured dimension-reduction map called the subsampled randomized Hadamard transform", "The formula R H D with sampling, Walsh-Hadamard and random signs is the standard form; the abstract names the map but not its factors."),
    input: C("t", "a structured dimension-reduction map"),
    output: C("t", "a structured dimension-reduction map"),
    preserved: C("t", "the map preserves the Euclidean geometry of an entire subspace of vectors"),
    broken: U("Vacuous: \"full matrix (compressed)\"."),
  }),
  g("D8-143", { p: W("Persistent_data_structure") }, {
    name: U("Node splitting is the Driscoll, Sarnak, Sleator and Tarjan technique for full persistence (from memory); the source found names the paper but not the technique."),
    description: U("Not settled by the source found."),
    input: U("Not settled by the source found."),
    output: U("Not settled by the source found."),
    preserved: U("Not settled by the source found."),
    broken: U("Not settled by the source found."),
  }),
  g("D8-125", { d: W("Data_transformation_(statistics)"), p: W("Principal_component_analysis") }, {
    name: X("d", "both the area and population data have been transformed using the logarithm function", "The name is the log transform; the content describes principal component analysis. Name and content are misaligned."),
    description: X("d", "both the area and population data have been transformed using the logarithm function", "Describes PCA (\"PCA on data matrix\"), not a log transform."),
    input: X("d", "both the area and population data have been transformed using the logarithm function", "A data matrix for PCA; a log transform takes positive data."),
    output: X("d", "both the area and population data have been transformed using the logarithm function", "Principal components; a log transform returns log-scaled data."),
    preserved: X("d", "both the area and population data have been transformed using the logarithm function", "\"Variance explained\" belongs to PCA."),
    broken: X("d", "both the area and population data have been transformed using the logarithm function", "Belongs to PCA."),
  }),
  // D7: authored fills (mapfill/d7-*.js)
  g("D7-376", { o: "https://arxiv.org/abs/1703.10857" }, {
    name: C("o", "These data accessors are collectively known as optics", "Setters are a kind of optic; the abstract does not name them."),
    description: U("The setter's type is standard in the Haskell lens literature; the source found does not state it."),
    input: U("\"Functorial structure\" is loose; not settled by the source."),
    output: U("Not settled by the source."),
    preserved: U("Not settled by the source."),
    broken: U("Not settled by the source."),
  }),
  g("D7-290", { s: W("Sheaf_(mathematics)") }, {
    name: C("s", "called the sheafification or sheaf associated to the presheaf"),
    description: C("s", "is the left adjoint functor to the inclusion functor (or forgetful functor) from the category of sheaves to the category of presheaves", "The plus-construction-twice clause is standard but not stated here."),
    input: C("s", "It takes a presheaf"),
    output: C("s", "and produces a new sheaf"),
    preserved: U("Exactness and stalk preservation are standard but not stated by the source."),
    broken: U("Vacuous."),
  }),
  g("D7-212", { p: W("Graded_poset") }, {
    name: C("p", "admits a grading if and only if all maximal chains in P have the same length"),
    description: C("p", "admits a grading if and only if all maximal chains in P have the same length"),
    input: C("p", "A bounded poset"),
    output: C("p", "equipped with a rank function"),
    preserved: C("p", "all maximal chains in P have the same length"),
    broken: U("A no-loss claim; nothing to check."),
  }),
  g("D7-123", { l: "https://arxiv.org/abs/1701.00260", b: "https://arxiv.org/abs/2104.11808" }, {
    name: C("l", "It follows that the Siggers term is the weakest non-trivial loop condition"),
    description: C("b", "two independent proofs of the CSP Dichotomy Theorem", "The equivalence with a Taylor term follows from Siggers being the weakest non-trivial condition; the displayed identity is not in the abstracts."),
    input: C("b", "the Constraint Satisfaction Problem (CSP)"),
    output: C("l", "the Siggers term is the weakest non-trivial loop condition"),
    preserved: C("l", "the Siggers term is the weakest non-trivial loop condition"),
    broken: U("A no-loss claim."),
  }),
  g("D7-052", { b: W("Braided_monoidal_category") }, {
    name: C("b", "equipped with a braiding"),
    description: C("b", "a commutativity constraint"),
    input: C("b", "equipped with a braiding"),
    output: C("b", "a commutativity constraint"),
    preserved: C("b", "that satisfies axioms including the hexagon identities"),
    broken: C("b", "A braided monoidal category is called symmetric if", "Symmetry is an extra condition, so a braiding squared need not be the identity."),
  }),
  g("D7-275", { t: W("Triangulated_category") }, {
    name: C("t", "It follows from the other axioms that an exact triangle (and in particular the object Z) is determined up to isomorphism by the morphism"),
    description: C("t", "although not always up to a unique isomorphism"),
    input: C("t", "is determined up to isomorphism by the morphism"),
    output: C("t", "an exact triangle"),
    preserved: U("Long exact sequences under homological functors are standard; not stated in the matched text."),
    broken: C("t", "although not always up to a unique isomorphism", "Non-unique isomorphism is why the cone is not functorial."),
  }),
  g("D7-183", { f: W("Filter_(mathematics)") }, {
    name: C("f", "is a filter, called the principal filter at"),
    description: C("f", "is a filter, called the principal filter at"),
    input: C("f", "is a filter, called the principal filter at"),
    output: C("f", "is a filter, called the principal filter at"),
    preserved: U("Order-reversing embedding into filters is correct but not stated by the source."),
    broken: U("A no-loss claim."),
  }),
  g("D7-129", { d: W("Distributive_property") }, {
    name: C("d", "x \\cdot (y + z) = x \\cdot y + x \\cdot z"),
    description: C("d", "x \\cdot (y + z) = x \\cdot y + x \\cdot z"),
    input: C("d", "x \\cdot (y + z) = x \\cdot y + x \\cdot z"),
    output: C("d", "x \\cdot (y + z) = x \\cdot y + x \\cdot z"),
    preserved: C("d", "x \\cdot (y + z) = x \\cdot y + x \\cdot z"),
    broken: U("Vacuous: \"term length and shape\"."),
  }),
  g("D7-339", { p: W("Postnikov_system") }, {
    name: C("p", "A Postnikov system of a path-connected space"),
    description: C("p", "induces an isomorphism"),
    input: C("p", "A Postnikov system of a path-connected space"),
    output: C("p", "that are fibrations with Eilenberg-MacLane spaces"),
    preserved: C("p", "induces an isomorphism"),
    broken: C("p", "In short, we are decomposing the homotopy type of X using an inverse s", "Each stage kills the homotopy above n."),
  }),
  g("D7-192", { p: W("Priestley_space") }, {
    name: C("p", "between the category of Priestley spaces and the category of bounded distributive lattices"),
    description: C("p", "Priestley spaces play a fundamental role in the study of distributive lattices", "The prime-filter construction of the dual space is standard; not in the matched text."),
    input: C("p", "the category of bounded distributive lattices"),
    output: C("p", "between the category of Priestley spaces"),
    preserved: C("p", "Each open up-set of", "Clopen up-sets recover the lattice."),
    broken: U("A no-loss claim for a dual equivalence."),
  }),
  g("D7-235", { m: W("Mapping_cylinder") }, {
    name: C("m", "Mapping cylinders are central to the definition of cofibrations"),
    description: C("m", "is a deformation retract of"),
    input: C("m", "Mapping cylinders are central to the definition of cofibrations"),
    output: C("m", "is a deformation retract of"),
    preserved: C("m", "is a deformation retract of"),
    broken: U("\"Strictness of Y\" is loose; not settled by the source."),
  }),
  g("D7-252", { c: W("Galois_cohomology") }, {
    name: C("c", "uer group, and the implications seem to have been well known to algebraists of the 1930s", "The source's history of Galois cohomology."),
    description: C("c", "In another direction, that of torsors", "Indirect: torsors and forms (quadratic forms, simple algebras) appear as the objects the theory classifies."),
    input: U("Field and Galois module: standard, not in the matched text."),
    output: U("Not in the matched text."),
    preserved: C("c", "such as quadratic forms, simple algebras", "Indirect."),
    broken: U("A no-loss claim."),
  }),
  g("D7-302", { n: "https://ncatlab.org/nlab/show/comprehension+category" }, {
    name: C("n", "A comprehension category consists of a strictly commutative triangle of functors"),
    description: U("The attribution (Lawvere, Jacobs) and the subobject reading are standard; not settled by the matched text."),
    input: U("Not settled by the matched text."),
    output: C("n", "A comprehension category consists of a strictly commutative triangle of functors"),
    preserved: U("Vacuous: \"membership\"."),
    broken: U("A no-loss claim."),
  }),
  g("D7-402", { k: W("Killing_form") }, {
    name: C("k", "Symmetric bilinear form in mathematics"),
    description: C("k", "which states that the Killing form is non-degenerate if and only if the Lie algebra is a direct sum of simple Lie algebras"),
    input: C("k", "Consider a Lie al"),
    output: C("k", "Symmetric bilinear form in mathematics"),
    preserved: C("k", "is invariant"),
    broken: U("A no-loss claim."),
  }),
  g("D7-318", { d: W("Double-negation_translation") }, {
    name: C("d", "is a general approach for embedding classical logic into intuitionistic logic"),
    description: C("d", "the Gödel–Gentzen translation and Kuroda's translation for first-order logic", "The topos-theoretic clause is not in the matched text."),
    input: C("d", "is a general approach for embedding classical logic into intuitionistic logic"),
    output: C("d", "is a general approach for embedding classical logic into intuitionistic logic"),
    preserved: C("d", "in classical logic if and only if T"),
    broken: U("Loss of disjunction and existence properties is standard; not stated in the matched text."),
  }),
  // Missing homes: authored fills (mapfill/homes.js)
  g("D8-222", {}, {
    name: U("Uniform row sampling as a sketch is standard in randomized linear algebra; no source found that settles this entry."),
    description: U("Not settled by a source found."),
    input: U("Not settled by a source found."),
    output: U("Not settled by a source found."),
    preserved: U("The coherence condition is correct from memory; not settled by a source found."),
    broken: U("Not settled by a source found."),
  }),
  g("D8-102", { z: W("Z-transform") }, {
    name: C("z", "The inverse Z-transform is"),
    description: C("z", "The inverse Z-transform is", "The contour integral is the source's displayed formula; the partial-fraction and series methods are not in the matched text."),
    input: C("z", "The inverse Z-transform is"),
    output: C("z", "the Z-transform converts a discrete-time signal, which is a sequence of real or complex n"),
    preserved: U("Invertibility given the region is standard; not in the matched text."),
    broken: U("A no-loss claim."),
  }),
  g("D8-169", { q: W("Quotient_graph") }, {
    name: C("q", "a quotient graph Q of a graph G is a graph whose vertices are blocks of a partition of the vertices of G"),
    description: C("q", "a quotient graph Q of a graph G is a graph whose vertices are blocks of a partition of the vertices of G"),
    input: C("q", "blocks of a partition of the vertices of G"),
    output: C("q", "is a graph whose vertices are blocks of a partition"),
    preserved: C("q", "where block B is adjacent to block C if some vertex in B is adj"),
    broken: C("q", "a graph whose vertices are blocks of a partition of the vertices of G", "Edges inside a block have no image."),
  }),
  g("D8-040", { h: "https://arxiv.org/abs/1501.01652" }, {
    name: C("h", "computing the discrete Hankel transform of order"),
    description: I("h", "evaluating Schlömilch and Fourier--Bessel expansions", "Sampling at Bessel zeros is one standard definition (Fourier-Bessel); the source treats several discretizations, so the fill's single definition is narrower than the term."),
    input: U("Not settled by the source."),
    output: U("Not settled by the source."),
    preserved: U("\"Approximate energy\" is not settled by the source."),
    broken: U("Not settled by the source."),
  }),
  g("D2-036", { z: W("Zonal_spherical_function") }, {
    name: C("z", "Zonal spherical functions have been explicitly determined for real semisimple groups by Harish-Chandra"),
    description: C("z", "is the K-biinvariant continuous function of compact support", "The spherical transform setting (K-bi-invariant functions, spherical functions) is stated; the reduction to the Cartan subspace modulo the Weyl group is not in the matched text."),
    input: C("z", "is the K-biinvariant continuous function of compact support"),
    output: U("Weyl-invariant function on a*: standard, not in the matched text."),
    preserved: C("z", "they were obtained in full generality in the 1960s in terms of Harish-Chandra's c-function", "The Plancherel theorem with the c-function."),
    broken: U("Not settled by the source."),
  }),
  g("D8-234", { z: W("Z-transform") }, {
    name: C("z", "the Z-transform converts a discrete-time signal, which is a sequence of real or complex n"),
    description: C("z", "Z-transform is derived from the Laplace transform"),
    input: C("z", "which is a sequence of real or complex n"),
    output: C("z", "discrete spatial domain signal into complex frequency domain representation"),
    preserved: U("Convolution theorem and region-of-convergence invertibility are standard; not in the matched text."),
    broken: U("Not settled by the matched text."),
  }),
  g("D8-163", { p: W("Principal_component_analysis") }, {
    name: C("p", "Principal component analysis (PCA) is a linear dimensionality reduction technique"),
    description: C("p", "The first principal component can equivalently be defined as a direction that maximizes the variance of the projected data"),
    input: C("p", "The data are linearly transformed onto a new coordinate system"),
    output: C("p", "The data are linearly transformed onto a new coordinate system such that the directions (principal comp"),
    preserved: C("p", "a direction that maximizes the variance of the projected data"),
    broken: C("p", "is a linear dimensionality reduction technique", "Linear: non-linear structure is not captured."),
  }),
  g("D8-140", { m: W("Mycielskian") }, {
    name: C("m", "The construction preserves the property of being triangle-free but increases the chromatic number"),
    description: C("m", "The construction preserves the property of being triangle-free but increases the chromatic number"),
    input: C("m", "The Mycielski graph μ(G) contains G itself as a subgraph"),
    output: C("m", "has 2n+1 vertices and 3m+n edges"),
    preserved: C("m", "The only new triangles in μ(G) are of the form", "Clique number is preserved when G has an edge; for an edgeless G it rises from 1 to 2. The fill omits that case."),
    broken: C("m", "but increases the chromatic number"),
  }),
  g("D8-101", { b: W("Two-sided_Laplace_transform") }, {
    name: C("b", "The inverse transformation then represents a synthesis of the signal as the sum of its frequency components"),
    description: C("b", "the above definition converges in a strip", "The Bromwich contour inside the strip is standard; the matched text states the strip and the inverse."),
    input: C("b", "the above definition converges in a strip"),
    output: C("b", "The inverse transformation then represents a synthesis of the signal"),
    preserved: U("Invertibility given the strip: standard, not in the matched text."),
    broken: U("Ambiguity without the strip: standard, not in the matched text."),
  }),
  g("D8-058", { f: W("Finite_difference_method") }, {
    name: C("f", "finite-difference methods (FDM) are a class of numerical techniques for solving differential equations by approximating derivatives with finite differences"),
    description: C("f", "are approximated by solving algebraic equations containing finite differences and values from nearby points"),
    input: C("f", "for solving differential equations"),
    output: C("f", "by solving algebraic equations containing finite differences"),
    preserved: U("Consistency and conservation are standard; not in the matched text."),
    broken: C("f", "truncation error or discretization error, the difference between the exact solution of the original"),
  }),
];

module.exports = { GRADES };
