// Role: targeted receipts. Grades for map entries outside the random sample, receipted because a
//   composite anchors on them. Same grading rules as audit/grades-0_1.js; kept out of the sample's error
//   estimates, since entries chosen for use are not a random draw.
// Contract: exports TARGETED = [{ id, why, sources: { key: url }, fields: { name, description, input,
//   output, preserved, broken: { verdict, src?, quote?, note? } } }]. Checked by scripts/audit.mjs; quotes
//   checked live by --verify-quotes, like the sample's.
// Invariant: data only. Grades are claims about entries, never edits to them.
"use strict";

const C = (src, quote, note) => ({ verdict: "confirmed", src, quote, ...(note ? { note } : {}) });
const I = (src, quote, note) => ({ verdict: "imprecise", src, quote, note });
const t = (id, why, sources, fields) => ({ id, why, sources, fields });
const W = (x) => `https://en.wikipedia.org/w/index.php?action=raw&title=${x}`;
const N = (x) => `https://ncatlab.org/nlab/source/${x}`;
const X = (src, quote, note) => ({ verdict: "wrong", src, quote, note });
const U = (note) => ({ verdict: "unsupported", note });
const M = (path) => `https://raw.githubusercontent.com/leanprover-community/mathlib4/380f2aafb622cb2c1c93dac545b6389083c68c51/${path}`;
const USE = "Requested by a composite; receipted.";
const CITE = "Citation pass 1: entries with a Mathlib counterpart, graded against a source and linked in mapfill/formal.js.";
const CITE2 = "Citation pass 2: the formal queue (reports/FORMAL-QUEUE.md), graded against a source and linked to Mathlib.";
const CHAIN = "Weakest link: a composite rests on this entry's unchecked claims (scripts/compose.mjs).";

const TARGETED = [
  t("D2-117", USE, { b: W("Blowing_up") }, {
    name: C("b", "blowing up or blowup is a type of geometric transformation"),
    description: I("b", "which replaces a subspace of a given space with the space of all directions pointing out of that subspace",
      "The locus need not be singular: any closed subscheme (or submanifold) can be blown up. \"Fundamental birational surgery\" is right: the source calls blowups the most fundamental transformation in birational geometry."),
    input: C("b", "let X be a scheme, and let", "The general input is a scheme with a coherent sheaf of ideals; a variety with a closed subvariety is the classical case."),
    output: C("b", "to replace the blow-up locus Z with the exceptional divisor E"),
    preserved: C("b", "is a birational mapping which, away from", "Birational, hence the same function field."),
    broken: C("b", "It is not difficult to show that E intersects itself negatively.",
      "What changes is more than local structure at Z: Z is replaced by a divisor of negative self-intersection (for a point on a surface, a (-1)-curve), and the topology changes (over C a connected sum with a reversed projective plane; over R a Moebius strip)."),
  }),
  t("D2-118", USE, { c: W("Castelnuovo%27s_contraction_theorem"), i: W("Intersection_theory") }, {
    name: C("c", "This contraction morphism is sometimes called a blowdown, which is the inverse operation of blowup."),
    description: C("c", "This contraction morphism is sometimes called a blowdown, which is the inverse operation of blowup."),
    input: I("c", "which means a smooth rational curve of self-intersection number",
      "\"Contractible exceptional\" hides the condition. On a smooth projective surface, contraction to a smooth point needs a (-1)-curve (Castelnuovo). Other curves contract, when they do, to singular points: a (-2)-curve to a Du Val point."),
    output: C("c", "has been contracted to one point"),
    preserved: C("c", "this morphism is an isomorphism outside"),
    broken: C("i", "-curve is the exceptional curve of some blow-up",
      "What is lost is recoverable: the contracted curve is the exceptional curve of the blow-up at its image point. The Stacks Project defines a contraction exactly so (Tag 0C5J: X is the blowing up of X' at x)."),
  }),
  t("D7-068", USE, { r: N("reflective+subcategory"), a: N("Aufhebung") }, {
    name: I("a", "whose reflection preserves finite limits",
      "In the nLab's usage (Lawvere's), a localization is a reflective subcategory whose reflector is left exact. A bare reflective subcategory is not yet a localization in that sense, and a composite built on this entry needs the left exact kind."),
    description: C("r", "The reflector in that case is the sheafification functor."),
    input: C("r", "A _reflective subcategory_ is a full subcategory"),
    output: C("r", "The left adjoint is sometimes called the __reflector__"),
    preserved: C("r", "A reflective subcategory is always closed under limits which exist in the ambient category"),
    broken: C("r", "When the unit of the reflector is a monomorphism",
      "The unit can add (a monomorphism, as in completion) or kill (an epimorphism, as in abelianization); the entry's gloss holds."),
  }),
  t("D7-284", USE, { e: N("essential+geometric+morphism") }, {
    name: C("e", "it is an **essential geometric morphism** if the"),
    description: C("e", "but also a left adjoint"),
    input: C("e", "Given a geometric morphism"),
    output: C("e", "f_! \\dashv f^* \\dashv f_*"),
    preserved: C("e", "of an essential geometric morphism preserves small limits since it is a right adjoint",
      "Limits because the inverse image is now a right adjoint; colimits because it was already a left adjoint."),
    broken: I("e", "is essential iff $f^\\ast$ preserves small limits iff $f^\\ast$ preserves small products",
      "Essentiality is a property of the geometric morphism (a condition on its inverse image, with the extra left adjoint determined up to isomorphism), not extra structure. \"Nothing is broken\" stands."),
  }),
  t("D7-288", USE, { l: N("Lawvere-Tierney+topology") }, {
    name: C("l", "a closure operator given by a left exact idempotent monad on the internal meet-semilattice"),
    description: C("l", "a closure operator given by a left exact idempotent monad on the internal meet-semilattice",
      "Inflationary and idempotent (a monad on the truth values), meet-preserving (left exact): the entry's three conditions."),
    input: C("l", "a Lawvere-Tierney topology on $E$, the inclusion"),
    output: C("l", "is itself a topos"),
    preserved: C("l", "which has a left exact left adjoint functor", "Sheafification, the left adjoint, preserves finite limits: the inclusion of j-sheaves is a geometric embedding, the left exact localization a composite built on this entry needs."),
    broken: C("l", "which amounts to the same thing as a natural closure operator on subobjects", "Subobjects with the same closure are identified among the j-sheaves: the truth values j collapses."),
  }),
  t("D4-176", USE, { h: W("Hodge_theory"), z: W("Helmholtz_decomposition") }, {
    name: C("h", "A variant of the Hodge theorem is the Hodge decomposition."),
    description: C("h", "The Hodge decomposition is a generalization of the Helmholtz decomposition for the de Rham complex.",
      "The map's formula is the standard one; for vector fields in three dimensions it is the Helmholtz (Leray) decomposition used in the Navier-Stokes cascade."),
    input: C("h", "on a closed Riemannian manifold as a sum of three parts in the form"),
    output: C("h", "this gives an orthogonal direct sum decomposition"),
    preserved: C("z", "has an orthogonal decomposition", "The L^2 orthogonality of gradient and curl parts is the invariant the PDE program uses: a pressure gradient pairs to zero with any curl."),
    broken: I("h", "there is a unique decomposition of any differential form",
      "A decomposition breaks nothing: it is an isomorphism onto the direct sum. What loses information is projecting onto one part (as the Leray projection discards the gradient part)."),
  }),
  // Citation pass 1.
  t("D1-003", CITE, { l: W("Line_graph") }, {
    name: C("l", "the line graph of an undirected graph"),
    description: C("l", "only four behaviors are possible for this sequence",
      "Every claim checks: edges become vertices, adjacency is sharing an endpoint, an Euler cycle gives a Hamiltonian line graph, iteration has four behaviours, and Whitney's theorem with the K_3 and K_{1,3} exception."),
    input: C("l", "the line graph of an undirected graph"),
    output: C("l", "their corresponding edges share a common endpoint"),
    preserved: I("l", "not all Hamiltonian cycles in line graphs come from Euler cycles in this way",
      "Edge count becoming vertex count is right. \"Eulerian translates to Hamiltonian\" holds one way only: an Eulerian graph has a Hamiltonian line graph, but a Hamiltonian line graph need not come from an Eulerian graph."),
    broken: C("l", "and the number of edges of", "The source gives the line graph's vertex and edge counts from the original's, which change as the entry says."),
  }),
  t("D1-059", CITE, { d: W("Dual_matroid") }, {
    name: C("d", "the dual of a matroid"),
    description: C("d", "These two operations are dual", "The complement description of bases, the deletion and contraction duality, and the planar-graph statement all check."),
    input: C("d", "the dual of a matroid"),
    output: C("d", "its basis sets are the complements of the basis sets of"),
    preserved: C("d", "the matroids representable over any other field, and the regular matroids, are all self-dual families",
      "Same ground set and the matroid axioms are stated in the same article; representability over a field passes to the dual."),
    broken: C("d", "then the rank function of the dual matroid is", "r*(E) = |E| - r(E), the entry's rank formula, at S = E."),
  }),
  t("D1-099", CITE, { g: W("Galois_connection") }, {
    name: C("g", "we will refer to them as (monotone) Galois connections and antitone Galois connections"),
    description: X("g", "are the associated closure operators; they are monotone idempotent maps with the property",
      "The entry states antitone maps but gives the monotone convention's second inequality, f(g(b)) <= b. For an antitone connection the source gives b <= FG(b). As written the definition is neither convention. The claim about matroid flats is not checked."),
    input: C("g", "be two partially ordered sets."),
    output: C("g", "monotone Galois connections are special cases of pairs of adjoint functors",
      "Adjunction is the monotone reading; an antitone connection is an adjunction between one poset and the other's opposite."),
    preserved: C("g", "are the associated closure operators; they are monotone idempotent maps with the property",
      "Right for the antitone convention the entry names: both composites are closure operators. In the monotone convention one is a kernel operator."),
    broken: C("g", "every Galois connection gives rise to an isomorphism of certain sub-posets",
      "Only the closed elements correspond; the rest of the order is not preserved."),
  }),
  t("D2-031", CITE, { m: W("Mellin_transform") }, {
    name: C("m", "the Mellin transform is an integral transform"),
    description: C("m", "may be regarded as the multiplicative version of the two-sided Laplace transform"),
    input: C("m", "the Mellin transform is an integral transform", "The transform takes a function on the positive reals; Mathlib's definition integrates over (0, infinity)."),
    output: C("m", "is defined to be the largest open strip on which it is defined"),
    preserved: I("m", "which is invariant under dilation",
      "Multiplicative convolution to product is right. \"Scale invariance\" is loose: the measure dx/x is dilation invariant, but the transform is not; dilating f by a multiplies the transform by a^(-s) (the source's scaling row; Mathlib's mellin_comp_mul_left)."),
    broken: C("m", "which is translation invariant", "The two-sided Laplace transform is adapted to additive translation; the Mellin transform to dilation."),
  }),
  t("D2-103", CITE, { t: W("Tensor_product_of_modules") }, {
    name: C("t", "the tensor product of modules is a construction"),
    description: C("t", "The universal property of a tensor product has the following important consequence"),
    input: C("t", "can be carried out for a pair of modules over a commutative ring",
      "Over a noncommutative ring the construction pairs a right and a left module and yields an abelian group."),
    output: C("t", "the tensor product of modules is a construction"),
    preserved: C("t", "are always right exact functors", "Right exactness is stated; bilinear maps out of M x N become linear maps out of the product."),
    broken: I("t", "can be written, non-uniquely,",
      "\"Individual presentations\" is loose. What is lost is uniqueness: an element is a sum of pure tensors in many ways."),
  }),
  t("D3-033", CITE, { u: W("Ultraproduct") }, {
    name: C("u", "ultraproducts uses an index set"),
    description: C("u", "any first-order formula is true in the ultraproduct if and only if the set of indices"),
    input: C("u", "and an ultrafilter"),
    output: C("u", "which compares components only relative to the ultrafilter"),
    preserved: C("u", "any first-order formula is true in the ultraproduct if and only if the set of indices"),
    broken: C("u", "then the ultraproduct will again be well-founded",
      "The source's example shows a property that is not first-order, well-foundedness, surviving only under an extra hypothesis (sigma-completeness)."),
  }),
  t("D3-116", CITE, { s: W("Sheaf_(mathematics)") }, {
    name: C("s", "called the sheafification or sheaf associated to the presheaf"),
    description: C("s", "is the left adjoint functor to the inclusion functor"),
    input: C("s", "It takes a presheaf"),
    output: C("s", "produces a new sheaf"),
    preserved: I("s", "there is a unique morphism of sheaves",
      "The universal property is right. The sheaf condition is not preserved but produced: the input is a presheaf. On a presheaf that is already a sheaf, sheafification changes nothing (up to isomorphism)."),
    broken: C("s", "It turns out that there is a best possible way to do this",
      "Sheafification identifies sections that agree locally and adds sections glued from compatible local ones."),
  }),
  t("D4-153", CITE, { g: W("Gelfand%E2%80%93Naimark%E2%80%93Segal_construction") }, {
    name: C("g", "construction establishes a correspondence between cyclic"),
    description: C("g", "construction establishes a correspondence between cyclic"),
    input: C("g", "Given a state"),
    output: C("g", "with distinguished unit cyclic vector"),
    preserved: C("g", "with distinguished unit cyclic vector",
      "The state is recovered as the vector state of the cyclic vector. Mathlib's GNS file lists this recovery as future work at the pinned commit."),
    broken: U("\"Abstract algebra\" names no invariant. What a single state's representation can lose is faithfulness (it may have a kernel); the source does not say so on the lines checked."),
  }),
  t("D4-264", CITE, { n: W("Nerve_(category_theory)"), m: M("Mathlib/AlgebraicTopology/SimplicialSet/NerveAdjunction.lean") }, {
    name: C("n", "of a small category C is a simplicial set"),
    description: C("n", "consists of the k-tuples of composable morphisms"),
    input: C("n", "of a small category C is a simplicial set"),
    output: C("n", "of a small category C is a simplicial set"),
    preserved: I("m", "is fully faithful, demonstrating that",
      "The category is recoverable for every small category, not only for groupoids: the nerve functor is fully faithful (Mathlib, CategoryTheory.nerveFunctor.fullyfaithful)."),
    broken: X("n", "does not erase or otherwise disregard morphisms obtained by composition",
      "Nothing is broken: composition is recorded by the 2-simplices, and the nerve functor is fully faithful. What the nerve adds is higher simplices, which are determined by the 2-simplices."),
  }),
  t("D7-157", CITE, { n: W("Normal_closure_(group_theory)") }, {
    name: C("n", "the normal closure of a subset"),
    description: C("n", "is the smallest normal subgroup of G containing S", "The field-extension reading is a separate construction with its own article."),
    input: C("n", "the normal closure of a subset"),
    output: C("n", "is the smallest normal subgroup of G containing S"),
    preserved: C("n", "is the smallest normal subgroup of G containing S"),
    broken: C("n", "is the subgroup generated by the set", "It is generated by all conjugates of elements of S, so S and its conjugates are not told apart."),
  }),
  t("D4-048", CHAIN, { c: W("%C4%8Cech_complex"), n: W("Nerve_complex") }, {
    name: C("c", "is an abstract simplicial complex constructed from a point cloud in any metric space"),
    description: I("c", "the nerve theorem provides a guarantee that the Čech complex is homotopy equivalent to union of the balls in the complex.",
      "\"Exact topology\" overstates it: the nerve theorem gives the homotopy type of the union of the balls, not its topology, and only when every nonempty intersection of the balls is contractible (a good cover), as for balls in Euclidean space. The source's \"any metric space\" is loose in the same way."),
    input: C("c", "Take the elements of X as the vertex set of"),
    output: C("c", "is an abstract simplicial complex constructed from a point cloud in any metric space"),
    preserved: C("c", "the nerve theorem provides a guarantee that the Čech complex is homotopy equivalent to union of the balls in the complex.",
      "Under the good-cover condition (conditions.js), as for Euclidean balls."),
    broken: I("c", "Take the elements of X as the vertex set of",
      "The points survive, as the vertex set. What is lost is their positions and distances, beyond which balls intersect."),
  }),
  t("D4-075", CHAIN, { k: W("Cone_(topology)") }, {
    name: C("k", "the cone of a topological space"),
    description: C("k", "every cone is contractible to the vertex point by the homotopy",
      "The source collapses the end X x {0} rather than X x {1}; the convention does not matter. For empty X the landed formula X x [0,1] / (X x {1}) is empty, while the source's definition (attach the cylinder to a point) gives the point; the claims below need X nonempty or the source's definition."),
    input: C("k", "the cone of a topological space"),
    output: C("k", "every cone is contractible to the vertex point by the homotopy"),
    preserved: I("k", "embeds a space as a subspace of a contractible space",
      "Contractibility is not preserved from X: the cone is contractible whatever X is, so it is produced. What the cone preserves is X itself, embedded as the base."),
    broken: I("k", "embeds a space as a subspace of a contractible space",
      "X's topology is not lost (X embeds as a subspace); one end of the cylinder collapses to the vertex, and what is lost is X's homotopy type."),
  }),
  t("D4-086", CHAIN, { c: W("Covariant_derivative") }, {
    name: C("c", "is a way of specifying a derivative along tangent vectors of a manifold"),
    description: C("c", "can be used to define parallel transport of a vector"),
    input: C("c", "the covariant derivative is a way of introducing and working with a connection on a manifold"),
    output: C("c", "is a generalization of the directional derivative from vector calculus"),
    preserved: C("c", "obeys the product rule", "The product (Leibniz) rule is stated. Tensoriality in X is built into Mathlib's definition: the derivative of a section is a section of Hom(TM, V) (mapfill/formal.js)."),
    broken: C("c", "In general, covariant derivatives do not commute.", "\"Broken\" in general only: a flat connection is one whose covariant derivatives commute; curvature measures the failure."),
  }),
  // Citation pass 2.
  t("D1-058", CITE2, { m: W("Matroid_minor") }, {
    name: C("m", "the contraction of M by T, written M/T"),
    description: C("m", "The rank function of the contraction is", "The source contracts an independent set T; the entry's single element e is the case T = {e}."),
    input: C("m", "the contraction of M by T, written M/T"),
    output: C("m", "is the matroid on the underlying set"),
    preserved: C("m", "to be independent in the contraction if its union with this basis remains independent in M"),
    broken: C("m", "The rank function of the contraction is", "r'(E - e) = r(E) - r({e}): the rank drops by one unless e is a loop."),
  }),
  t("D2-071", CITE2, { g: W("Gram%E2%80%93Schmidt_process") }, {
    name: C("g", "the Gram–Schmidt process"),
    description: C("g", "a method of constructing an orthonormal basis from a set of vectors in an inner product space"),
    input: C("g", "takes a finite, linearly independent set of vectors"),
    output: C("g", "a method of constructing an orthonormal basis from a set of vectors in an inner product space"),
    preserved: C("g", "that spans the same"),
    broken: U("True (orthogonalizing changes angles, normalizing changes lengths), but the lines checked do not state it."),
  }),
  t("D2-072", CITE2, { l: W("Localization_(commutative_algebra)"), m: M("Mathlib/RingTheory/Localization/Ideal.lean") }, {
    name: C("l", "The localization of a commutative ring"),
    description: C("l", "The localization of a commutative ring"),
    input: C("l", "The localization of a commutative ring"),
    output: I("l", "is a local ring that is generally denoted",
      "S^{-1}R is a local ring when S is the complement of a prime ideal p (then it is R_p), not in general: localizing at S = {1} gives R back."),
    preserved: C("m", "p.IsPrime ∧ Disjoint (M : Set R) ↑p", "Primes of S^{-1}R correspond to primes of R disjoint from S (Mathlib's IsLocalization.orderIsoOfPrime)."),
    broken: U("\"Global structure\" names no invariant. What is lost is the primes meeting S, and the elements S kills."),
  }),
  t("D2-080", CITE2, { n: W("Noether_normalization_lemma") }, {
    name: C("n", "Noether normalization"),
    description: C("n", "is a finitely generated module over the polynomial ring"),
    input: C("n", "is a finitely generated module over the polynomial ring", "The input is a finitely generated algebra over a field k."),
    output: C("n", "is a finitely generated module over the polynomial ring"),
    preserved: C("n", "is equal to the Krull dimension of the ring"),
    broken: U("\"Specific generators\" is vague: the polynomial subring is chosen, not canonical, which the lines checked do not discuss."),
  }),
  t("D2-145", CITE2, { c: W("Coset") }, {
    name: C("c", "Together they partition the entire group"),
    description: C("c", "Together they partition the entire group"),
    input: C("c", "Together they partition the entire group"),
    output: C("c", "Together they partition the entire group"),
    preserved: C("c", "This common value is called the index of", "The index is quoted; G acting on G/H by left multiplication is Mathlib's MulAction.quotient (mapfill/formal.js)."),
    broken: C("c", "into equal-size, non-overlapping sets", "Elements of one coset are identified."),
  }),
  t("D2-168", CITE2, { s: W("Stone%E2%80%93%C4%8Cech_compactification"), b: M("Mathlib/Topology/Bases.lean") }, {
    name: C("s", "the Stone–Čech compactification is a technique for constructing a universal map"),
    description: C("s", "factors uniquely through"),
    input: C("s", "is a Tychonoff space, the map from", "For a Tychonoff (completely regular Hausdorff) space X embeds; otherwise the map need not be injective."),
    output: C("s", "can be identified as a dense subspace of"),
    preserved: C("s", "factors uniquely through"),
    broken: X("b", "protected theorem _root_.DenseRange.separableSpace [SeparableSpace α] [TopologicalSpace β]",
      "Separability is not broken: X has dense image in βX, so βX is separable when X is (proved in lean/MathMap/StoneCech.lean). Metrizability is lost (βℕ is not metrizable), which the lines checked do not state."),
  }),
  t("D2-180", CITE2, { g: W("Grothendieck_group") }, {
    name: C("g", "it is called the Grothendieck group of"),
    description: C("g", "Such an abelian group K always exists"),
    input: C("g", "it is called the Grothendieck group of"),
    output: C("g", "Such an abelian group K always exists"),
    preserved: C("g", "It is characterized by a certain universal property"),
    broken: C("g", "does not have the cancellation property", "The map M -> K(M) is injective exactly when M is cancellative."),
  }),
  t("D2-195", CITE2, { s: W("Snake_lemma") }, {
    name: C("s", "The snake lemma is a tool used in mathematics"),
    description: C("s", "to construct long exact sequences"),
    input: C("s", "In an abelian category"),
    output: C("s", "to construct long exact sequences"),
    preserved: C("s", "Homomorphisms constructed with its help are generally called connecting homomorphisms"),
    broken: U("\"Diagram structure\" names no invariant."),
  }),
  t("D2-196", CITE2, { f: W("Five_lemma") }, {
    name: C("f", "The five lemma states that"),
    description: I("f", "if the rows are exact, m and p are isomorphisms, l is an epimorphism, and q is a monomorphism, then n is also an isomorphism.",
      "The rows must be exact and the diagram commutative, which the entry omits; and less than four isomorphisms suffices: the outer maps need only be epi and mono."),
    input: I("f", "if the rows are exact", "Needs a commutative diagram with exact rows."),
    output: C("f", "then n is also an isomorphism."),
    preserved: C("f", "then n is also an isomorphism."),
    broken: U("\"Explicit construction\" names no invariant."),
  }),
  t("D3-035", CITE2, { f: W("Fra%C3%AFss%C3%A9_limit"), m: M("Mathlib/ModelTheory/Fraisse.lean") }, {
    name: C("f", "approximate a (countable) structure by its finitely generated substructures"),
    description: I("f", "is ω-categorical if and only if",
      "The limit is unique up to isomorphism, but ω-categorical only under a condition: for a finite language, exactly when the class is uniformly locally finite. The entry says it always is."),
    input: C("m", "amalgamation : Amalgamation K", "Mathlib's IsFraisse: nonempty, finitely generated, essentially countable, hereditary, joint embedding, amalgamation."),
    output: C("m", "protected ultrahomogeneous : IsUltrahomogeneous L M"),
    preserved: C("m", "protected ultrahomogeneous : IsUltrahomogeneous L M"),
    broken: C("f", "approximate a (countable) structure by its finitely generated substructures"),
  }),
  t("D3-114", CITE2, { y: W("Yoneda_lemma"), m: M("Mathlib/CategoryTheory/Yoneda.lean") }, {
    name: C("y", "It allows the embedding of any locally small category into a category of functors"),
    description: C("y", "It allows the embedding of any locally small category into a category of functors"),
    input: C("y", "It allows the embedding of any locally small category into a category of functors", "Locally small suffices; the entry's small category is a special case."),
    output: C("m", "def fullyFaithful : (yoneda (C := C)).FullyFaithful where"),
    preserved: C("m", "def fullyFaithful : (yoneda (C := C)).FullyFaithful where"),
    broken: U("\"Small category size\" names no invariant."),
  }),
  // Citation pass 3.
  t("D1-060", CITE2, { m: W("Matroid_minor") }, {
    name: C("m", "a minor of a matroid M is another matroid N that is obtained from M by a sequence of restriction and contraction operations"),
    description: I("m", "conjectured that the matroids representable over any particular finite field are well-quasi-ordered. So far this has been proven only for the matroids of bounded branchwidth.",
      "The entry states well-quasi-ordering for matroids representable over finite fields as a fact. The source gives it as a conjecture of Robertson and Seymour, proved for bounded branchwidth; Geelen, Gerards and Whittle announced a proof of the related Rota conjecture in 2014 but have not published it."),
    input: C("m", "is obtained from M by a sequence of restriction and contraction operations"),
    output: C("m", "a minor of a matroid M is another matroid N"),
    preserved: C("m", "shows that the minor ordering is not a well-quasi-ordering on all matroids", "Minor-closed properties survive by definition; representability over a field is minor-closed."),
    broken: C("m", "is obtained from M by a sequence of restriction and contraction operations"),
  }),
  t("D1-098", CITE2, { o: W("Order_isomorphism") }, {
    name: C("o", "an order isomorphism from"),
    description: C("o", "is a bijective function f from S to T with the property that, for every x"),
    input: C("o", "given two posets"),
    output: C("o", "is a bijective function f from S to T"),
    preserved: C("o", "by simply relabeling the vertices"),
    broken: C("o", "by simply relabeling the vertices", "Only the labels change."),
  }),
  t("D2-051", CITE2, { j: W("Jordan%E2%80%93Chevalley_decomposition") }, {
    name: C("j", "Jordan–Chevalley decomposition"),
    description: I("j", "potentially diagonalisable part is also characterised as the semisimple part.",
      "D is semisimple: diagonalizable over an extension field where the characteristic polynomial splits, not necessarily over the given field."),
    input: C("j", "If K is a perfect field, then every polynomial is a product of separable polynomials"),
    output: I("j", "potentially diagonalisable part is also characterised as the semisimple part.", "D is semisimple (potentially diagonalizable), as Mathlib states it."),
    preserved: C("j", "Jordan–Chevalley decomposition", "D and N are polynomials in A; D has A's eigenvalues."),
    broken: U("\"Single operator form\" names no invariant."),
  }),
  t("D2-073", CITE2, { c: W("Completion_of_a_ring") }, {
    name: C("c", "completion is the inverse limit of the factor rings,"),
    description: I("c", "completion is the inverse limit of the factor rings,",
      "The completion is the inverse limit of R/I^n, which is a formal power series ring only in cases like k[x] at (x). It extends R (the map R -> R-hat is injective) only when the powers of I intersect in zero."),
    input: C("c", "the filtration on a commutative ring R by the powers of a proper ideal I"),
    output: C("c", "completion is the inverse limit of the factor rings,"),
    preserved: C("c", "completion is the inverse limit of the factor rings,", "A ring map, and ideals extend."),
    broken: U("\"Finiteness, algebraic simplicity\" names no invariant; a completion of a Noetherian ring is Noetherian."),
  }),
  t("D2-078", CITE2, { i: W("Integral_element") }, {
    name: C("i", "is called the integral closure of A in B"),
    description: C("i", "integral closure is closely related with normalization and normal schemes"),
    input: C("i", "is called the integral closure of A in B"),
    output: C("i", "is called the integral closure of A in B"),
    preserved: C("i", "is called the integral closure of A in B", "The integral closure of a domain in its fraction field has the same fraction field."),
    broken: C("i", "integral closure is closely related with normalization and normal schemes", "Normalization resolves singularities in codimension one (all of them, for curves), not all singularities."),
  }),
  t("D2-110", CITE2, { p: W("Pontryagin_duality") }, {
    name: C("p", "The Pontryagin duality theorem establishes Pontryagin duality"),
    description: C("p", "any locally compact abelian group is naturally isomorphic with its bidual"),
    input: C("p", "any locally compact abelian group is naturally isomorphic with its bidual"),
    output: C("p", "The Pontryagin duality theorem establishes Pontryagin duality"),
    preserved: C("p", "any locally compact abelian group is naturally isomorphic with its bidual"),
    broken: U("\"Element structure\" names no invariant."),
  }),
  t("D2-112", CITE2, { s: W("Spectrum_of_a_ring") }, {
    name: C("s", "the prime spectrum (or simply the spectrum) of a commutative ring R is the set of all prime ideals of R"),
    description: C("s", "called the structure sheaf, which makes it a ringed space"),
    input: C("s", "the prime spectrum (or simply the spectrum) of a commutative ring R is the set of all prime ideals of R"),
    output: C("s", "equipped with a topology called the Zariski topology"),
    preserved: C("s", "called the structure sheaf, which makes it a ringed space", "Global sections of the structure sheaf recover R (Mathlib's AlgebraicGeometry.Scheme.ΓSpecIso)."),
    broken: U("\"Non-geometric properties\" names no invariant."),
  }),
  t("D2-153", CITE2, { m: W("Monad_(category_theory)") }, {
    name: C("m", "using the Eilenberg–Moore category"),
    description: C("m", "using the Eilenberg–Moore category"),
    input: C("m", "any monad can be found as an explicit adjunction of functors using the Eilenberg–Moore category"),
    output: C("m", "using the Eilenberg–Moore category"),
    preserved: C("m", "any monad can be found as an explicit adjunction of functors using the Eilenberg–Moore category"),
    broken: U("\"Underlying category\" names no invariant; the forgetful functor keeps it."),
  }),
  t("D2-154", CITE2, { k: W("Kleisli_category") }, {
    name: C("k", "a Kleisli category is a category naturally associated to any monad T"),
    description: C("k", "a Kleisli category is a category naturally associated to any monad T"),
    input: C("k", "a Kleisli category is a category naturally associated to any monad T"),
    output: C("k", "a Kleisli category is a category naturally associated to any monad T"),
    preserved: C("k", "It is equivalent to the category of free T-algebras."),
    broken: U("\"Original morphisms\": the Kleisli category has C's objects and new morphisms; C's morphisms embed through the free functor."),
  }),
  t("D2-188", CITE2, { a: W("Adjoint_functors") }, {
    name: C("a", "the adjoint functor theorem of Peter J. Freyd"),
    description: C("a", "the adjoint functor theorem of Peter J. Freyd"),
    input: C("a", "has a left adjoint if and only if it is continuous", "Needs a complete domain category, preservation of limits, and the solution set condition."),
    output: C("a", "the adjoint functor theorem of Peter J. Freyd"),
    preserved: C("a", "the adjoint functor theorem of Peter J. Freyd"),
    broken: U("\"Non-adjoint properties\" names no invariant."),
  }),
  // Citation pass 4.
  t("D4-010", CITE2, { c: W("Commutator_subgroup") }, {
    name: C("c", "is an abelian group called the abelianization of G"),
    description: C("c", "The quotient G/[G, G] is an abelian group called the abelianization of G"),
    input: C("c", "Given a group G , a quotient group G/N is abelian if and only if"),
    output: C("c", "The quotient G/[G, G] is an abelian group called the abelianization of G"),
    preserved: C("c", "a quotient group G/N is abelian if and only if [G, G]\\subseteq N", "Every abelian quotient factors through it; H_1 of a space is the abelianization of its fundamental group (Hurewicz), not stated on the lines checked."),
    broken: C("c", "The quotient G/[G, G] is an abelian group called the abelianization of G"),
  }),
  t("D4-072", CITE2, { k: W("Compact-open_topology"), m: M("Mathlib/Topology/CompactOpen.lean") }, {
    name: C("k", "is a topology defined on the set of continuous maps between two topological spaces"),
    description: C("k", "is a topology defined on the set of continuous maps between two topological spaces"),
    input: C("k", "is a topology defined on the set of continuous maps between two topological spaces"),
    output: C("k", "is one of the commonly used topologies on function spaces"),
    preserved: C("m", "instance [LocallyCompactPair X Y] : ContinuousEval C(X, Y) X Y where", "Evaluation is continuous under local compactness (Mathlib's condition is on the pair)."),
    broken: U("\"Pointwise topology\": the compact-open topology is finer than the pointwise one, which the lines checked do not state."),
  }),
  t("D4-127", CITE2, { e: W("Exterior_derivative") }, {
    name: C("e", "then d(d\\alpha)=0"),
    description: C("e", "then d(d\\alpha)=0"),
    input: C("e", "then d(d\\alpha)=0"),
    output: C("e", "then d(d\\alpha)=0"),
    preserved: C("e", "then d(d\\alpha)=0", "d∘d = 0 is stated; Stokes' theorem and de Rham cohomology rest on it."),
    broken: U("\"Non-exact forms\" names no invariant."),
  }),
  t("D4-249", CITE2, { m: W("Metrizable_space") }, {
    name: C("m", "Urysohn's metrization theorem"),
    description: C("m", "This states that every Hausdorff second-countable regular space is metrizable."),
    input: C("m", "This states that every Hausdorff second-countable regular space is metrizable."),
    output: C("m", "This states that every Hausdorff second-countable regular space is metrizable."),
    preserved: C("m", "This states that every Hausdorff second-countable regular space is metrizable."),
    broken: C("m", "every second-countable manifold is metrizable", "The metric is not unique; any compatible metric will do."),
  }),
  t("D4-273", CITE2, { a: W("Alexandroff_extension") }, {
    name: C("a", "the Alexandroff compactification"),
    description: C("a", "in a precise sense minimal among all compactific"),
    input: C("a", "is Hausdorff if and only if", "For a Hausdorff compactification X must be locally compact Hausdorff."),
    output: C("a", "is compact."),
    preserved: C("a", "it embeds X as an open subset of"),
    broken: C("a", "is dense in X^* , if X is noncompact."),
  }),
  t("D4-373", CITE2, { s: W("Stone%E2%80%93%C4%8Cech_compactification"), b: M("Mathlib/Topology/Bases.lean") }, {
    name: C("s", "the Stone–Čech compactification is a technique for constructing a universal map"),
    description: C("s", "factors uniquely through"),
    input: C("s", "is a Tychonoff space, the map from"),
    output: C("s", "can be identified as a dense subspace of"),
    preserved: C("s", "factors uniquely through"),
    broken: X("b", "protected theorem _root_.DenseRange.separableSpace [SeparableSpace α] [TopologicalSpace β]",
      "Separability is not broken (X is dense in βX; proved in lean/MathMap/StoneCech.lean). The same error as D2-168. Metrizability and cardinality do change (βℕ), which the lines checked do not state."),
  }),
  t("D4-427", CITE2, { w: W("Whitney_embedding_theorem") }, {
    name: C("w", "The strong Whitney embedding theorem states"),
    description: C("w", "The strong Whitney embedding theorem states"),
    input: C("w", "The strong Whitney embedding theorem states", "Compactness is not needed: any smooth m-manifold (Hausdorff, second countable) embeds in R^{2m}."),
    output: C("w", "The strong Whitney embedding theorem states"),
    preserved: C("w", "The strong Whitney embedding theorem states"),
    broken: U("\"Specific embedding (non-unique)\" is true but not stated on the lines checked."),
  }),
  t("D4-436", CITE2, { z: W("Zariski_topology") }, {
    name: C("z", "the topology whose closed sets are the algebraic subsets of the variety"),
    description: C("z", "the topology whose closed sets are the algebraic subsets of the variety"),
    input: C("z", "the topology whose closed sets are the algebraic subsets of the variety"),
    output: C("z", "the topology whose closed sets are the algebraic subsets of the variety"),
    preserved: C("z", "the topology whose closed sets are the algebraic subsets of the variety"),
    broken: C("z", "in particular, it is not Hausdorff."),
  }),
  t("D8-107", CITE, { j: W("Jordan_normal_form") }, {
    name: C("j", "its Jordan normal form is also called the Jordan normal form of"),
    description: C("j", "This condition is always satisfied if K is algebraically closed"),
    input: C("j", "Any square matrix has a Jordan normal form if the field of"),
    output: C("j", "The Jordan normal form is obtained by some similarity transformation"),
    preserved: C("j", "is called the algebraic multiplicity of", "Similar matrices share eigenvalues with their multiplicities, and the form is a similarity invariant."),
    broken: C("j", "its Jordan normal form is very sensitive to perturbations"),
  }),
];

module.exports = { TARGETED };
