// Role: the proof-assistant audit (FUNCTIONS.md F21). A formal result the repository claims rests on the
//   kernel and on no hole: every audited declaration uses only the standard three axioms (proved) or
//   carries sorryAx as an owed liability (stated), never another axiom, and the committed audit is the one
//   the current Lean sources produce.
// Contract: config `lean-audit: { project, audit, sources, declarations?, stated? }`: `project` the Lean
//   project directory, `audit` the committed audit file (shape of A-Viable-Fork/Math_Map lean/AUDIT.json:
//   { sources, decls: { name: { status, axioms } } }), `sources` the patterns hashed (lib/lean.mjs; Math_Map:
//   ["lakefile.toml", "lean-toolchain", "lake-manifest.json", "MathMap.lean", "MathMap/*.lean"]),
//   `declarations` names that must appear in the audit, `stated` "allow" (default; counted in a warning)
//   or "fail". Fails on a missing or stale audit, a declaration resting on a non-standard axiom, a status
//   that does not match its axioms, a required declaration absent from the audit, and, with stated "fail",
//   any sorryAx. Runs offline with no toolchain: the audit is regenerated by .infra/tools/lean-audit.mjs,
//   in CI, where Lean is installed.
// Invariant: read-only. Status is recomputed from the recorded axioms, never trusted from the file.
import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { result, errored } from "../lib/core.mjs";
import { sourcesHash, statusOf } from "../lib/lean.mjs";

export default function leanAudit(root, cfg = {}) {
  for (const k of ["project", "audit", "sources"]) if (!cfg[k]) return errored("lean-audit", `config names no ${k}`);
  if (!["allow", "fail", undefined].includes(cfg.stated)) return errored("lean-audit", `stated is "${cfg.stated}"; use "allow" or "fail"`);
  const ap = join(root, cfg.audit);
  if (!existsSync(ap)) return result("lean-audit", [`${cfg.audit} is missing: run node .infra/tools/lean-audit.mjs where Lean is installed`], "no audit");
  let A; try { A = JSON.parse(readFileSync(ap, "utf8")); } catch (e) { return result("lean-audit", [`${cfg.audit}: not JSON (${e.message})`], ""); }
  const fails = [], warnings = [], decls = A.decls || {};
  if (A.sources !== sourcesHash(join(root, cfg.project), cfg.sources)) fails.push(`${cfg.audit} is stale: the Lean sources changed since it was written`);
  let stated = 0;
  for (const [d, e] of Object.entries(decls)) {
    const axioms = e.axioms || [], s = statusOf(axioms);
    if (s !== e.status) fails.push(`${d}: recorded ${e.status}, but its axioms make it ${s}`);
    if (s === "axiom") fails.push(`${d}: rests on axioms beyond the standard three: ${axioms.join(", ")}`);
    if (s === "stated") { stated++; if (cfg.stated === "fail") fails.push(`${d}: rests on sorryAx`); }
  }
  for (const d of cfg.declarations || []) if (!(d in decls)) fails.push(`${d}: required but absent from ${cfg.audit}`);
  if (stated && cfg.stated !== "fail") warnings.push(`${stated} declaration(s) stated, not proved: owed liabilities`);
  const proved = Object.values(decls).filter((e) => statusOf(e.axioms || []) === "proved").length;
  return result("lean-audit", fails, `${Object.keys(decls).length} declarations, ${proved} proved, ${stated} stated`, warnings);
}
