// Role: renders the corrections report (FUNCTIONS.md F12), in the form of A-Viable-Fork/phone's.
// Contract: `node .infra/tools/corrections-report.mjs [--out reports/CORRECTIONS.md]` reads the
//   corrections configured in infra.json (default corrections/corrections.js) and writes the report. Keep
//   it fresh with a freshness entry: { "path": "reports/CORRECTIONS.md", "command": "node
//   .infra/tools/corrections-report.mjs" }.
// Invariant: writes only the report.
import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { loadConfig } from "../lib/core.mjs";
import { loadCorrections } from "../checks/corrections.mjs";

const root = resolve(join(dirname(fileURLToPath(import.meta.url)), "../.."));
const a = process.argv.slice(2), i = a.indexOf("--out");
const out = i >= 0 ? a[i + 1] : "reports/CORRECTIONS.md";
const cfg = loadConfig(root).checks?.corrections || {};
const list = loadCorrections(root, cfg) || [];
const L = ["# Corrections", "", "*Generated by `.infra/tools/corrections-report.mjs` from `" + (cfg.file || "corrections/corrections.js") + "`. Do not edit by hand.*", "",
  "A correction replaces a claim and keeps the record of what it replaced, why, and the receipt that settled it.", ""];
for (const c of list) {
  L.push(`## ${c.id} · ${c.status} · ${c.date}`, "", `In \`${c.file}\`.`, "", `Superseded: "${c.superseded}"`, "", `Now: "${c.text}"`, "", `Why: ${c.reason}`, "", `Carried in by: \`${c.source}\``, "");
  if (c.receipt) L.push(`Receipt: ${c.receipt.repo} \`${c.receipt.commit.slice(0, 7)}\`, \`${c.receipt.path}\`: "${c.receipt.quote}"`, "");
}
mkdirSync(dirname(join(root, out)), { recursive: true });
writeFileSync(join(root, out), L.join("\n"));
console.log(`corrections-report: wrote ${out} (${list.length} corrections)`);
