// Role: the paper catalogue. Checks catalogue/papers.json and renders reports/CATALOGUE.md, a checklist of
//   every paper the map cites and how deeply each has been read.
// Contract: `node scripts/catalogue.mjs [--check]`. Exit 1 on any failure; --check also fails if the report
//   is stale. Checks: ids unique; status valid; every named entry exists in map.json; `receipted` exactly
//   when the paper has excerpt files, each of which exists; `inspected-*` needs a note; `out-of-scope` needs
//   a note giving the reason; every paper excerpt in excerpts/ (arxiv-*, and journal pages) belongs to one
//   paper.
// Invariant: statuses grade how deeply this repository has read a paper, strongest first: receipted (quoted
//   verbatim in excerpts/), inspected-body, inspected-abstract, queued, out-of-scope.
import { readFileSync, writeFileSync, existsSync, readdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const C = JSON.parse(readFileSync(join(ROOT, "catalogue/papers.json"), "utf8"));
const MAP = JSON.parse(readFileSync(join(ROOT, "map.json"), "utf8"));
const ids = new Set(MAP.entries.map((e) => e.id));
const STATUS = ["receipted", "inspected-body", "inspected-abstract", "queued", "out-of-scope"];
const F = [], seen = new Set(), owned = new Map();
for (const p of C.entries) {
  if (seen.has(p.id)) F.push(`${p.id}: duplicate id`); seen.add(p.id);
  if (!STATUS.includes(p.status)) F.push(`${p.id}: status ${p.status}`);
  for (const e of p.entries || []) if (!ids.has(e)) F.push(`${p.id}: no map entry ${e}`);
  for (const x of p.excerpts || []) {
    if (!existsSync(join(ROOT, x))) F.push(`${p.id}: no file ${x}`);
    if (owned.has(x)) F.push(`${x}: claimed by ${owned.get(x)} and ${p.id}`); owned.set(x, p.id);
  }
  if ((p.status === "receipted") !== Boolean(p.excerpts?.length)) F.push(`${p.id}: receipted must match having excerpts`);
  if (/^inspected|out-of-scope/.test(p.status) && !p.note) F.push(`${p.id}: ${p.status} without a note`);
}
for (const f of readdirSync(join(ROOT, "excerpts"))) {
  if (/^(mathlib|nlab|wikipedia)-/.test(f)) continue;
  if (!owned.has(`excerpts/${f}`)) F.push(`excerpts/${f}: a paper excerpt with no catalogue entry`);
}
const by = (s) => C.entries.filter((p) => p.status === s).length;
const L = ["# Paper catalogue", "", "Generated by `scripts/catalogue.mjs` from `catalogue/papers.json`; do not edit.", "", C.scope, "",
  `${C.entries.length} papers: ${STATUS.map((s) => `${s} ${by(s)}`).join(", ")}.`, "",
  "Statuses grade how deeply this repository has read each paper: `receipted` (quoted verbatim in `excerpts/`), `inspected-body`, `inspected-abstract`, `queued`, `out-of-scope`.", ""];
for (const p of [...C.entries].sort((a, b) => STATUS.indexOf(a.status) - STATUS.indexOf(b.status) || a.id.localeCompare(b.id)))
  L.push(`- [${p.status === "queued" ? " " : "x"}] \`${p.id}\` ${p.title} (${p.authors}, ${p.year}) **${p.status}** · ${p.entries.join(", ")}${p.excerpts?.length ? ` · ${p.excerpts.join(", ")}` : ""}${p.note ? ` · ${p.note}` : ""}`);
const out = L.join("\n") + "\n", path = join(ROOT, "reports/CATALOGUE.md");
if (process.argv.includes("--check")) { if (!existsSync(path) || readFileSync(path, "utf8") !== out) F.push("reports/CATALOGUE.md is stale: run node scripts/catalogue.mjs"); }
else writeFileSync(path, out);
for (const f of F) console.log(`FAIL ${f}`);
if (F.length) { console.log(`catalogue: ${F.length} failure(s)`); process.exit(1); }
console.log(`catalogue: PASS (${C.entries.length} papers; ${STATUS.map((s) => `${s} ${by(s)}`).join(", ")})`);
