// Role: the formal layer's data. Links from map entries to Mathlib declarations at one pinned commit.
// Contract: exports MATHLIB = { commit } and FORMAL = [{ entry, field, decl, file, match, note }]. field is
//   the entry field the declaration bears on (description, input, output, preserved, broken); decl is the
//   full Lean name; file is its path in mathlib4; match grades how the statement bears on the claim
//   (exact, general, special, related, ingredient, conflicts; see scripts/formal.mjs). Optional: whole
//   (an exact link that states the whole field, not one claim in it), invariant (the named invariant, in
//   mapfill/invariants.js, whose claim the declaration proves) and premise (for a general link, the entry
//   field stating the hypothesis the theorem needs, such as "is a right adjoint"). Checked by
//   scripts/formal.mjs against excerpts/mathlib-*.txt, which that script writes from a pinned checkout.
// Invariant: data only. A link never edits an entry; a conflict is recorded here and in the audit grade.
"use strict";

const MATHLIB = { commit: "380f2aafb622cb2c1c93dac545b6389083c68c51" };

const K = (entry, field, decl, file, match, note, opts = {}) => ({ entry, field, decl, file, match, note, ...opts });
const ADJ = "Mathlib/CategoryTheory/Adjunction/Limits.lean";
const FORMAL = [
  // D1 Combinatorics
  K("D1-003", "output", "SimpleGraph.lineGraph", "Mathlib/Combinatorics/SimpleGraph/LineGraph.lean", "exact",
    "The line graph is a simple graph on G.edgeSet: its vertices are the edges of G, so edge count becomes vertex count by definition.", { whole: true }),
  K("D1-003", "description", "SimpleGraph.lineGraph_adj_iff_exists", "Mathlib/Combinatorics/SimpleGraph/LineGraph.lean", "exact",
    "Two edges are adjacent in L(G) iff they are distinct and share a vertex. The entry's further claims (Eulerian to Hamiltonian, Whitney's theorem) are not in Mathlib at the pin."),
  K("D1-059", "output", "Matroid.dual_isBase_iff'", "Mathlib/Combinatorics/Matroid/Dual.lean", "exact",
    "Bases of the dual are the complements, within the ground set, of bases of M.", { whole: true }),
  K("D1-059", "preserved", "Matroid.dual_ground", "Mathlib/Combinatorics/Matroid/Dual.lean", "exact", "The dual has the same ground set."),
  K("D1-059", "broken", "Matroid.eRank_add_eRank_dual", "Mathlib/Combinatorics/Matroid/Rank/ENat.lean", "exact",
    "r + r* = |E|, the entry's rank formula, stated in extended naturals so it covers infinite ground sets."),
  K("D1-099", "description", "GaloisConnection", "Mathlib/Order/GaloisConnection/Defs.lean", "conflicts",
    "Mathlib's Galois connection is the monotone convention: l a <= b iff a <= u b, giving a <= u(l a) and l(u b) <= b. The entry states antitone maps but gives the monotone pair of inequalities. For antitone maps the second must read b <= f(g(b)); with that correction both composites are closure operators, as the entry's preserved field says (in Mathlib, an antitone connection is a monotone one into the order dual)."),
  K("D1-099", "description", "GaloisConnection.le_u_l", "Mathlib/Order/GaloisConnection/Defs.lean", "related",
    "The unit inequality a <= g(f(a)), which holds in both conventions."),
  K("D1-099", "preserved", "GaloisConnection.closureOperator", "Mathlib/Order/Closure.lean", "special",
    "In the monotone convention only u after l is a closure operator (l after u is an interior operator). The entry's claim that both composites are closure operators is the antitone case."),
  // D2 Algebra
  K("D2-031", "description", "mellin", "Mathlib/Analysis/MellinTransform.lean", "exact", "The integral of t^(s-1) f(t) over (0, infinity): the entry's kernel."),
  K("D2-031", "preserved", "mellin_comp_mul_left", "Mathlib/Analysis/MellinTransform.lean", "related",
    "Mathlib gives the exact law: dilating f by a multiplies the transform by a^(-s). \"Scale invariance\" holds only for the modulus on the line Re s = 0. The convolution-to-product rule the entry also claims is not in Mathlib at the pin."),
  K("D2-103", "description", "TensorProduct.lift.unique", "Mathlib/LinearAlgebra/TensorProduct/Basic.lean", "related",
    "The universal property: a linear map out of the tensor product is determined by its values on pure tensors, and lift realizes each bilinear map."),
  K("D2-103", "preserved", "rTensor_exact", "Mathlib/LinearAlgebra/TensorProduct/RightExactness.lean", "exact",
    "Right exactness: tensoring an exact sequence ending in a surjection gives an exact sequence."),
  // D3 Logic
  K("D3-033", "preserved", "FirstOrder.Language.Ultraproduct.sentence_realize", "Mathlib/ModelTheory/Ultraproducts.lean", "exact",
    "Los's theorem: the ultraproduct satisfies a sentence iff U-almost every factor does.", { whole: true }),
  K("D3-116", "description", "CategoryTheory.sheafificationAdjunction", "Mathlib/CategoryTheory/Sites/Sheafification.lean", "exact",
    "Sheafification is left adjoint to the inclusion of sheaves into presheaves, given that sheafification exists for the coefficient category (HasWeakSheafify), a hypothesis the entry leaves implicit."),
  // D4 Topology
  K("D4-153", "output", "PositiveLinearMap.gnsStarAlgHom", "Mathlib/Analysis/CStarAlgebra/GelfandNaimarkSegal.lean", "exact",
    "The GNS representation of the algebra on the completion of A with the inner product given by the positive functional. State recovery through a cyclic vector, the entry's preserved claim, is listed as future work in the file at the pin.", { whole: true }),
  K("D4-264", "output", "CategoryTheory.nerveFunctor", "Mathlib/AlgebraicTopology/SimplicialSet/Nerve.lean", "exact", "The nerve functor from categories to simplicial sets."),
  K("D4-264", "preserved", "CategoryTheory.nerveFunctor.fullyfaithful", "Mathlib/AlgebraicTopology/SimplicialSet/NerveAdjunction.lean", "exact",
    "The nerve functor is fully faithful on all small categories, so functors between categories are exactly maps of their nerves: the corrected field. (The landed field restricted this to groupoids, which is unnecessary.)", { invariant: "category-structure", whole: true }),
  // D6 Analysis
  K("D6-117", "output", "MeasureTheory.Measure.haveLebesgueDecomposition_add", "Mathlib/MeasureTheory/Measure/Decomposition/Lebesgue.lean", "exact",
    "mu = singular part + nu.withDensity (Radon-Nikodym derivative), given that a Lebesgue decomposition exists.", { whole: true }),
  K("D6-117", "description", "MeasureTheory.Measure.mutuallySingular_singularPart", "Mathlib/MeasureTheory/Measure/Decomposition/Lebesgue.lean", "exact", "The singular part is mutually singular with nu."),
  K("D6-117", "input", "MeasureTheory.Measure.haveLebesgueDecomposition_of_sigmaFinite", "Mathlib/MeasureTheory/Measure/Decomposition/Lebesgue.lean", "special",
    "The decomposition exists when mu is s-finite and nu is sigma-finite. The entry's input (\"measures mu, nu\") omits this hypothesis."),
  // D7 Category theory
  K("D7-068", "input", "CategoryTheory.Reflective", "Mathlib/CategoryTheory/Adjunction/Reflective.lean", "exact",
    "A reflective subcategory: a fully faithful functor with a left adjoint.", { whole: true }),
  K("D7-068", "preserved", "CategoryTheory.monadicOfReflective", "Mathlib/CategoryTheory/Monad/Adjunction.lean", "general",
    "A reflective inclusion is monadic, and monadic functors create limits (monadicCreatesLimits): limits in R are computed in C."),
  K("D7-068", "preserved", "CategoryTheory.monadicCreatesLimits", "Mathlib/CategoryTheory/Monad/Limits.lean", "general", "With monadicOfReflective, the inclusion creates limits.", { invariant: "limits", premise: "input" }),
  K("D7-157", "preserved", "Subgroup.normalClosure_normal", "Mathlib/Algebra/Group/Subgroup/Basic.lean", "exact", "The normal closure is normal.", { whole: true }),
  K("D7-157", "description", "Subgroup.normalClosure_le_normal", "Mathlib/Algebra/Group/Subgroup/Basic.lean", "related",
    "It is the smallest normal subgroup containing the set. The field-extension reading is a separate construction (IntermediateField.normalClosure), not linked here."),
  K("D7-157", "output", "Subgroup.normalClosure", "Mathlib/Algebra/Group/Subgroup/Basic.lean", "exact", "Defined as the subgroup generated by all conjugates of the set."),
  K("D7-X02", "preserved", "CategoryTheory.Sheaf.createsLimits", "Mathlib/CategoryTheory/Sites/Limits.lean", "special",
    "For a Grothendieck topology, the inclusion of sheaves into presheaves creates limits. Grothendieck topologies give the subtoposes of presheaf toposes; the general Lawvere-Tierney case is not in Mathlib at the pin."),
  K("D7-X02", "description", "CategoryTheory.preservesFiniteLimits_presheafToSheaf", "Mathlib/CategoryTheory/Sites/LeftExact.lean", "special",
    "Sheafification is left exact, for Grothendieck topologies and coefficient categories meeting the stated hypotheses."),
  // The categorical chain: adjoints preserve limits and colimits, applied to each step's functor.
  K("D7-X02", "preserved", "CategoryTheory.Adjunction.rightAdjoint_preservesLimits", ADJ, "general",
    "Any right adjoint preserves limits; the inclusion of a subtopos is right adjoint to sheafification (the entry's description).", { invariant: "limits", premise: "description" }),
  K("D7-284", "preserved", "CategoryTheory.Adjunction.rightAdjoint_preservesLimits", ADJ, "general",
    "f^* is right adjoint to f_! in the essential triple, so it preserves limits.", { invariant: "limits", premise: "output" }),
  K("D7-284", "preserved", "CategoryTheory.Adjunction.leftAdjoint_preservesColimits", ADJ, "general",
    "f^* is left adjoint to f_* in the triple, so it preserves colimits.", { invariant: "colimits", premise: "output" }),
  K("D7-X03", "preserved", "CategoryTheory.Adjunction.rightAdjoint_preservesLimits", ADJ, "general",
    "In the triple i_! left of i^* left of i_*, the middle functor i^* is a right adjoint, so it preserves limits.", { invariant: "limits", premise: "input" }),
  K("D7-X03", "preserved", "CategoryTheory.Adjunction.leftAdjoint_preservesColimits", ADJ, "general",
    "The middle functor i^* is also a left adjoint, so it preserves colimits.", { invariant: "colimits", premise: "input" }),
  // D4-086: Mathlib's covariant derivative (a Koszul connection on a vector bundle).
  K("D4-086", "preserved", "IsCovariantDerivativeOn", "Mathlib/Geometry/Manifold/VectorBundle/CovariantDerivative/Basic.lean", "exact",
    "The Leibniz rule is a field of Mathlib's definition: cov (g • σ) = g • cov σ + dg ⊗ σ.", { invariant: "leibniz-rule" }),
  K("D4-086", "preserved", "IsCovariantDerivativeOn", "Mathlib/Geometry/Manifold/VectorBundle/CovariantDerivative/Basic.lean", "exact",
    "Tensoriality in X is built into the type: the covariant derivative of a section is, at each point, a continuous linear map from the tangent space.", { invariant: "tensoriality" }),
  // Citation pass 2: the formal queue.
  K("D1-058", "output", "Matroid.contract_ground", "Mathlib/Combinatorics/Matroid/Minor/Contract.lean", "general", "The contraction's ground set is E minus the contracted set."),
  K("D1-058", "description", "Matroid.dual_contract", "Mathlib/Combinatorics/Matroid/Minor/Contract.lean", "general", "Contraction is dual to deletion: (M / X)* = M* \\ X."),
  K("D1-058", "preserved", "Matroid.IsNonloop.contractElem_indep_iff", "Mathlib/Combinatorics/Matroid/Minor/Contract.lean", "special",
    "For a non-loop e, I is independent in M / e iff e is not in I and I + e is independent in M: independence relative to e."),
  K("D2-071", "output", "InnerProductSpace.gramSchmidtNormed_orthonormal", "Mathlib/Analysis/InnerProductSpace/GramSchmidtOrtho.lean", "exact", "The normalized Gram-Schmidt vectors of a linearly independent family are orthonormal.", { whole: true }),
  K("D2-071", "preserved", "InnerProductSpace.span_gramSchmidt", "Mathlib/Analysis/InnerProductSpace/GramSchmidtOrtho.lean", "exact", "The span is preserved."),
  K("D2-072", "output", "IsLocalization.AtPrime.isLocalRing", "Mathlib/RingTheory/Localization/AtPrime/Basic.lean", "exact",
    "The localization is a local ring when S is the complement of a prime: the hypothesis the landed output omits."),
  K("D2-072", "preserved", "IsLocalization.orderIsoOfPrime", "Mathlib/RingTheory/Localization/Ideal.lean", "exact", "Prime ideals of S^{-1}R correspond, order-preservingly, to primes of R disjoint from S."),
  K("D2-075", "output", "FractionRing.field", "Mathlib/RingTheory/Localization/FractionRing.lean", "exact", "The field of fractions is a field.", { whole: true }),
  K("D2-075", "preserved", "IsFractionRing.injective", "Mathlib/RingTheory/Localization/FractionRing.lean", "exact", "R -> Frac(R) is injective."),
  K("D2-075", "description", "IsFractionRing.lift", "Mathlib/RingTheory/Localization/FractionRing.lean", "related", "Any injective map to a field factors through Frac(R): it is the smallest field containing R."),
  K("D2-080", "output", "exists_finite_inj_algHom_of_fg", "Mathlib/RingTheory/NoetherNormalization.lean", "exact",
    "A finitely generated algebra over a field contains a polynomial ring in s variables (an injective algebra map) over which it is finite.", { whole: true }),
  K("D2-145", "preserved", "MulAction.quotient", "Mathlib/GroupTheory/GroupAction/Quotient.lean", "general", "G acts on G/H."),
  K("D2-145", "preserved", "Subgroup.index", "Mathlib/GroupTheory/Index.lean", "exact", "The index [G : H] is the cardinality of G/H."),
  K("D2-168", "output", "denseRange_stoneCechUnit", "Mathlib/Topology/Compactification/StoneCech.lean", "exact", "X has dense image in its Stone-Cech compactification."),
  K("D2-168", "preserved", "stoneCechExtend_extends", "Mathlib/Topology/Compactification/StoneCech.lean", "exact", "Continuous maps to compact Hausdorff spaces extend.", { whole: true }),
  K("D2-168", "broken", "DenseRange.separableSpace", "Mathlib/Topology/Bases.lean", "conflicts",
    "A space with a dense image of a separable space is separable, so the Stone-Cech compactification of a separable space is separable: the landed text lists separability as broken."),
  K("D2-180", "output", "Algebra.GrothendieckGroup.instCommGroup", "Mathlib/GroupTheory/MonoidLocalization/GrothendieckGroup.lean", "exact", "K(M) is an abelian group.", { whole: true }),
  K("D2-180", "preserved", "Algebra.GrothendieckGroup.of", "Mathlib/GroupTheory/MonoidLocalization/GrothendieckGroup.lean", "exact", "M maps to K(M) by a monoid homomorphism."),
  K("D2-180", "broken", "Algebra.GrothendieckGroup.of_injective", "Mathlib/GroupTheory/MonoidLocalization/GrothendieckGroup.lean", "related", "The map is injective when M is cancellative; without cancellation, elements are identified."),
  K("D2-195", "output", "CategoryTheory.ShortComplex.SnakeInput.snake_lemma", "Mathlib/Algebra/Homology/ShortComplex/SnakeLemma.lean", "exact", "The snake sequence is exact.", { whole: true }),
  K("D2-195", "preserved", "CategoryTheory.ShortComplex.SnakeInput.δ", "Mathlib/Algebra/Homology/ShortComplex/SnakeLemma.lean", "exact", "The connecting map."),
  K("D2-196", "description", "MonoidHom.bijective_of_surjective_of_bijective_of_bijective_of_injective", "Mathlib/Algebra/FiveLemma.lean", "special",
    "The sharp five lemma for groups (with exact rows and commuting squares): surjective, bijective, bijective, injective outer maps make the middle one bijective. Four isomorphisms is a special case."),
  K("D3-035", "input", "FirstOrder.Language.IsFraisse", "Mathlib/ModelTheory/Fraisse.lean", "general", "A Fraisse class: nonempty, finitely generated, essentially countable, hereditary, joint embedding, amalgamation."),
  K("D3-035", "output", "FirstOrder.Language.IsFraisseLimit", "Mathlib/ModelTheory/Fraisse.lean", "exact", "A countable ultrahomogeneous structure with age K.", { whole: true }),
  K("D3-035", "description", "FirstOrder.Language.IsFraisseLimit.nonempty_equiv", "Mathlib/ModelTheory/Fraisse.lean", "exact", "Two Fraisse limits of the same class are isomorphic: uniqueness."),
  K("D3-114", "output", "CategoryTheory.Yoneda.fullyFaithful", "Mathlib/CategoryTheory/Yoneda.lean", "exact", "The Yoneda embedding is fully faithful.", { whole: true }),
  K("D3-114", "preserved", "CategoryTheory.Yoneda.fullyFaithful", "Mathlib/CategoryTheory/Yoneda.lean", "exact", "Full faithfulness, the preserved claim's first part."),
  // Citation pass 3.
  K("D1-060", "output", "Matroid.IsMinor", "Mathlib/Combinatorics/Matroid/Minor/Order.lean", "exact", "The minor relation."),
  K("D1-060", "description", "Matroid.IsMinor.trans", "Mathlib/Combinatorics/Matroid/Minor/Order.lean", "related", "A minor of a minor is a minor: any sequence of deletions and contractions gives a minor."),
  K("D1-098", "description", "OrderIso.le_iff_le", "Mathlib/Order/Hom/Basic.lean", "exact", "e x ≤ e y iff x ≤ y."),
  K("D2-051", "output", "Module.End.exists_isNilpotent_isSemisimple", "Mathlib/LinearAlgebra/JordanChevalley.lean", "conflicts",
    "Over a perfect field Mathlib's decomposition has a semisimple part, not a diagonalizable one: the landed output says diagonalizable, which needs the characteristic polynomial to split."),
  K("D2-073", "description", "AdicCompletion.of_injective_iff", "Mathlib/RingTheory/AdicCompletion/Basic.lean", "exact",
    "The map into the completion is injective exactly when the module is I-adically Hausdorff: the condition under which completion extends R."),
  K("D2-110", "description", "AddChar.doubleDualEmb_bijective", "Mathlib/Analysis/Fourier/FiniteAbelian/PontryaginDuality.lean", "special",
    "Pontryagin duality for finite abelian groups: the map to the double dual is bijective. The locally compact case is not in Mathlib at the pin."),
  K("D2-112", "preserved", "AlgebraicGeometry.Scheme.ΓSpecIso", "Mathlib/AlgebraicGeometry/Scheme.lean", "exact", "Global sections of Spec R recover R.", { whole: true }),
  K("D2-112", "output", "AlgebraicGeometry.Spec", "Mathlib/AlgebraicGeometry/Scheme.lean", "exact", "Spec R is a scheme (an affine one).", { whole: true }),
  K("D2-153", "preserved", "CategoryTheory.Monad.adj", "Mathlib/CategoryTheory/Monad/Algebra.lean", "exact", "The free and forgetful functors between C and its Eilenberg-Moore category are adjoint."),
  K("D2-153", "output", "CategoryTheory.Monad.Algebra", "Mathlib/CategoryTheory/Monad/Algebra.lean", "exact", "An algebra for a monad: an object with a structure map satisfying unit and associativity.", { whole: true }),
  K("D2-154", "output", "CategoryTheory.Kleisli", "Mathlib/CategoryTheory/Monad/Kleisli.lean", "ingredient", "The object type of the Kleisli category (morphisms and composition are separate declarations).", {}),
  K("D2-154", "preserved", "CategoryTheory.Kleisli.Adjunction.adj", "Mathlib/CategoryTheory/Monad/Kleisli.lean", "related", "The Kleisli adjunction, whose monad is T."),
  K("D2-188", "description", "CategoryTheory.isRightAdjoint_of_preservesLimits_of_solutionSetCondition", "Mathlib/CategoryTheory/Adjunction/AdjointFunctorTheorems.lean", "exact",
    "Freyd's general adjoint functor theorem: a limit-preserving functor from a complete category satisfying the solution set condition is a right adjoint.", { whole: true }),
  K("D7-290", "description", "CategoryTheory.GrothendieckTopology.sheafify", "Mathlib/CategoryTheory/Sites/ConcreteSheafification.lean", "exact", "Sheafification is the plus construction applied twice.", { whole: true }),
  K("D7-290", "description", "CategoryTheory.sheafificationAdjunction", "Mathlib/CategoryTheory/Sites/Sheafification.lean", "exact", "Sheafification is left adjoint to the inclusion.", { whole: true }),
  K("D4-414", "description", "VectorBundleCore", "Mathlib/Topology/VectorBundle/Basic.lean", "ingredient", "A vector bundle given by base sets and transition functions (coordinate changes) satisfying the cocycle condition."),
  // Citation pass 4.
  K("D4-010", "output", "Abelianization", "Mathlib/GroupTheory/Abelianization/Defs.lean", "exact", "G modulo its commutator subgroup.", { whole: true }),
  K("D4-010", "preserved", "Abelianization.of", "Mathlib/GroupTheory/Abelianization/Defs.lean", "ingredient", "The quotient homomorphism G -> G^ab."),
  K("D4-072", "output", "ContinuousMap.compactOpen", "Mathlib/Topology/CompactOpen.lean", "exact", "The compact-open topology on continuous maps.", { whole: true }),
  K("D4-127", "preserved", "extDeriv_extDeriv", "Mathlib/Analysis/Calculus/DifferentialForm/Basic.lean", "special", "d∘d = 0 for sufficiently smooth forms on a normed space (Mathlib at the pin: forms on vector spaces, not yet on manifolds)."),
  K("D4-249", "description", "TopologicalSpace.metrizableSpace_of_t3_secondCountable", "Mathlib/Topology/Metrizable/Urysohn.lean", "exact", "Urysohn: a second-countable regular (T3) space is metrizable.", { whole: true }),
  K("D4-273", "preserved", "OnePoint.isOpenEmbedding_coe", "Mathlib/Topology/Compactification/OnePoint/Basic.lean", "exact", "X embeds as an open subspace: its local topology is kept.", { whole: true }),
  K("D4-273", "broken", "OnePoint.denseRange_coe", "Mathlib/Topology/Compactification/OnePoint/Basic.lean", "related", "For noncompact X the image is dense: X is no longer the whole space, and is no longer closed."),
  K("D4-373", "output", "denseRange_stoneCechUnit", "Mathlib/Topology/Compactification/StoneCech.lean", "exact", "X has dense image in βX."),
  K("D4-373", "preserved", "stoneCechExtend_extends", "Mathlib/Topology/Compactification/StoneCech.lean", "exact", "Continuous maps to compact Hausdorff spaces extend.", { whole: true }),
  K("D4-373", "broken", "DenseRange.separableSpace", "Mathlib/Topology/Bases.lean", "conflicts", "The Stone-Cech compactification of a separable space is separable; the landed text lists separability as broken."),
  K("D4-427", "description", "SmoothBumpCovering.embeddingPiTangent_injective", "Mathlib/Geometry/Manifold/WhitneyEmbedding.lean", "related",
    "Mathlib has the weak Whitney theorem (a compact manifold embeds in some Euclidean space via bump functions), not the embedding in R^{2n}."),
  K("D4-436", "output", "PrimeSpectrum.isClosed_iff_zeroLocus", "Mathlib/RingTheory/Spectrum/Prime/Topology.lean", "exact", "The closed sets of Spec R are the zero loci.", { whole: true }),
  // Citation pass 5.
  K("D2-193", "output", "Ideal.quotientInfRingEquivPiQuotient", "Mathlib/RingTheory/Ideal/Quotient/Operations.lean", "exact", "For pairwise coprime ideals, R modulo their intersection is isomorphic to the product of the quotients.", { whole: true }),
  K("D8-022", "output", "Nat.chineseRemainder", "Mathlib/Data/Nat/ModEq.lean", "exact", "For coprime moduli, a number with the given residues (two moduli; the general case iterates).", { whole: true }),
  K("D8-022", "preserved", "Nat.chineseRemainder_modEq_unique", "Mathlib/Data/Nat/ModEq.lean", "exact", "Uniqueness modulo the product."),
  K("D4-041", "description", "cantorSet", "Mathlib/Topology/Instances/CantorSet.lean", "ingredient", "The middle-thirds Cantor set in the reals; Mathlib does not state its homeomorphism with 2^ω or the universality claim at the pin."),
  K("D7-199", "description", "zorn_le", "Mathlib/Order/Zorn.lean", "exact", "If every chain is bounded above, there is a maximal element.", { whole: true }),
  K("D6-023", "input", "IsStarNormal.instContinuousFunctionalCalculus", "Mathlib/Analysis/CStarAlgebra/ContinuousFunctionalCalculus/Basic.lean", "exact", "Normal elements of a C*-algebra have a continuous functional calculus.", { whole: true }),
  K("D6-023", "preserved", "cfc_map_spectrum", "Mathlib/Analysis/CStarAlgebra/ContinuousFunctionalCalculus/Unital.lean", "exact", "Spectral mapping: the spectrum of f(a) is f applied to the spectrum of a."),
  K("D6-023", "output", "cfcHom", "Mathlib/Analysis/CStarAlgebra/ContinuousFunctionalCalculus/Unital.lean", "exact", "The *-homomorphism from continuous functions on the spectrum to the algebra."),
  K("D6-090", "output", "MeasureTheory.Measure.haveLebesgueDecomposition_add", "Mathlib/MeasureTheory/Measure/Decomposition/Lebesgue.lean", "special", "Mathlib has the two-part decomposition (absolutely continuous plus singular); the three-part refinement is not stated."),
  K("D4-408", "description", "Pi.compactSpace", "Mathlib/Topology/Compactness/Compact.lean", "exact", "Tychonoff: a product of compact spaces is compact.", { whole: true }),
  K("D5-030", "output", "Diffeomorph", "Mathlib/Geometry/Manifold/Diffeomorph.lean", "exact", "A bijection that is C^n with C^n inverse, between manifolds.", { whole: true }),
  // D8 Computation
  K("D8-125", "preserved", "Real.strictMonoOn_log", "Mathlib/Analysis/SpecialFunctions/Log/Basic.lean", "exact", "The logarithm is strictly increasing on the positive reals, so the transform preserves order (the corrected field).", { whole: true }),
  K("D8-125", "description", "Real.log_mul", "Mathlib/Analysis/SpecialFunctions/Log/Basic.lean", "exact", "log(xy) = log x + log y: products become sums (the corrected field)."),
  K("D8-107", "description", "Module.End.exists_isNilpotent_isSemisimple", "Mathlib/LinearAlgebra/JordanChevalley.lean", "related",
    "Mathlib has the Jordan-Chevalley decomposition (f = nilpotent + semisimple, over a perfect field), which the Jordan normal form implies. The normal form itself is not in Mathlib at the pin. The name also matches Mathlib's Jordan decomposition of signed measures, a different theorem."),
];

module.exports = { MATHLIB, FORMAL };
