// Role: authored fills for the map's missing homes. These entries point ("See Domain N home entry") at a
//   home entry that was never written; each home is written once here and attached to every entry that
//   points at it. See mapfill/README.md for the contract.
"use strict";
const { G } = require("./fill.js");

module.exports = [
  // Integral and discrete transforms (the D6 homes that do not exist)
  ...G([["D2-017", "Rectangular Mask STFT"], ["D5-115", "Rectangular mask STFT"], ["D7-424", "Rectangular Mask Short-Time Fourier Transform"], ["D8-179", "Rectangular mask short-time Fourier transform"]],
    "Short-time Fourier transform with a rectangular (boxcar) window: the Fourier transform of each windowed segment.", "Signal f, window length", "Time-frequency coefficients", "Energy up to window normalization; invertibility with sufficient overlap", "Frequency resolution (sidelobe leakage from the sharp window)"),
  ...G([["D2-028", "Two-sided Laplace Transform"], ["D3-162", "Two-sided Laplace transform"], ["D5-141", "Two-sided Laplace transform"], ["D7-436", "Two-Sided Laplace Transform"], ["D8-221", "Two-sided Laplace transform"]],
    "The bilateral Laplace transform F(s) = integral over R of f(t) e^{-s t} dt, converging in a vertical strip; contains the Fourier transform on the imaginary axis and the moment generating function.", "Function f on R", "Analytic function F(s) on a strip", "Convolution to product; information (invertible within the strip)", "Causality information unless the strip is specified"),
  ...G([["D2-029", "Inverse Two-sided Laplace Transform"], ["D3-163", "Inverse two-sided Laplace transform"], ["D5-071", "Inverse two-sided Laplace transform"], ["D8-101", "Inverse two-sided Laplace transform"]],
    "Recovers f from its bilateral Laplace transform by a Bromwich integral along a vertical line inside the strip of convergence.", "Analytic F(s) and its strip of convergence", "Function f on R", "Information (inverse of the transform)", "Nothing, given the strip; without it the inverse is ambiguous"),
  ...G([["D2-033", "Poisson-Mellin-Newton Cycle"], ["D3-167", "Poisson-Mellin-Newton cycle"], ["D4-303", "Poisson-Mellin-Newton cycle"], ["D8-155", "Poisson-Mellin-Newton cycle"]],
    "The triangle of correspondences between Poisson generating functions, Mellin transforms and Newton (finite difference) series used in the analysis of algorithms (Flajolet and coauthors): a sequence's asymptotics read from the poles of a Mellin transform via Rice's integrals.", "Sequence or generating function", "Asymptotic expansion via Mellin poles", "Asymptotic information", "Exact values (only asymptotics survive)", { reading: "Recorded from memory of the analytic-combinatorics literature." }),
  ...G([["D2-036", "Harish-Chandra Transform"]],
    "The spherical transform on a reductive group: integrates a K-bi-invariant function against spherical functions, reducing harmonic analysis on G/K to Fourier analysis on a Cartan subspace modulo the Weyl group.", "K-bi-invariant function on G", "Weyl-invariant function on a*", "Convolution to product; Plancherel (with Harish-Chandra's c-function)", "Non-K-invariant information"),
  ...G([["D2-038", "Fourier-Stieltjes Transform"]],
    "The Fourier transform of a finite measure: mu-hat(xi) = integral e^{-i x xi} d mu(x). Characteristic functions of probability measures are the case of positive mass one.", "Finite Borel measure mu", "Bounded uniformly continuous function mu-hat", "Convolution to product; measure determined (uniqueness); positive definiteness (Bochner)", "Decay (mu-hat need not vanish at infinity)"),
  ...G([["D2-039", "Z-transform"], ["D5-149", "Z-transform"], ["D7-464", "Z-Transform"], ["D8-234", "Z-transform"]],
    "Transforms a sequence x_n to X(z) = sum x_n z^{-n}, converging in an annulus; the discrete analogue of the Laplace transform.", "Sequence (x_n)", "Function X(z) on an annulus", "Convolution to product; information within the region of convergence", "Causality information unless the region is specified"),
  ...G([["D8-102", "Inverse Z-transform"]],
    "Recovers a sequence from its Z-transform by contour integration, partial fractions or power series expansion in the region of convergence.", "X(z) with its region of convergence", "Sequence (x_n)", "Information", "Nothing, given the region"),
  ...G([["D3-171", "Discrete cosine transform"], ["D7-454", "Discrete Cosine Transform"], ["D8-038", "Discrete Cosine Transform (DCT)"]],
    "Expresses a finite real sequence as a sum of cosines at discrete frequencies (DCT-II in common use); concentrates the energy of smooth signals in few coefficients (JPEG).", "Real sequence of length N", "Real coefficient sequence of length N", "Energy (orthonormal version); invertibility", "Locality in the sample domain"),
  ...G([["D3-172", "Modified discrete cosine transform"], ["D8-137", "Modified discrete cosine transform"]],
    "A lapped transform on overlapping blocks (2N inputs to N outputs) whose aliasing cancels between neighbors (Princen-Bradley); used in audio codecs.", "Overlapping blocks of a signal", "Critically sampled coefficients", "Perfect reconstruction with overlap-add (time-domain aliasing cancellation)", "Invertibility of a single block"),
  ...G([["D3-184", "Stirling transform"], ["D5-135", "Stirling transform"], ["D7-463", "Stirling Transform"], ["D8-204", "Stirling transform"]],
    "Transforms a sequence a_k to b_n = sum S(n, k) a_k with Stirling numbers of the second kind; the inverse uses the signed first kind. On exponential generating functions it is composition with e^x - 1.", "Sequence (a_n)", "Sequence (b_n)", "Information (invertible)", "Nothing"),
  ...G([["D4-175", "Hilbert-Schmidt integral operator"], ["D5-061", "Hilbert-Schmidt integral operator"], ["D7-431", "Hilbert-Schmidt Integral Operator"], ["D8-093", "Hilbert-Schmidt integral operator"]],
    "The integral operator (K f)(x) = integral k(x, y) f(y) dy with square-integrable kernel; compact, and the kernel's L^2 norm equals the Hilbert-Schmidt norm.", "Kernel k in L^2(X x Y), function f in L^2(Y)", "Function K f in L^2(X)", "Linearity; compactness; square-summable singular values", "Invertibility (compact operators on infinite-dimensional spaces are not invertible)"),
  ...G([["D5-073", "Irrational base DWT"]],
    "The irrational-base discrete weighted transform (Crandall and Fagin): a weighted FFT that performs multiplication modulo 2^p - 1 without zero padding; used in Mersenne prime searches.", "Large integers modulo 2^p - 1", "Their product modulo 2^p - 1", "The modular product", "Nothing (exact up to rounding control)"),
  ...G([["D8-040", "Discrete Hankel transform"]],
    "A discretization of the Hankel transform sampling at zeros of Bessel functions, approximately orthogonal; radial Fourier analysis on grids.", "Samples of a radial function", "Samples of its Hankel transform", "Approximate energy; invertibility (up to discretization)", "Exact continuous values"),
  ...G([["D8-035", "Daubechies wavelet transform"]],
    "Discrete wavelet transform with Daubechies' compactly supported orthogonal wavelets of maximal vanishing moments for their support.", "Discrete signal", "Wavelet coefficients by scale and position", "Energy (orthogonal); polynomial reproduction up to the vanishing moments", "Symmetry of the filters"),
  ...G([["D8-201", "Square root transform"]],
    "Applies y = sqrt(x), a variance-stabilizing transform for Poisson counts (Anscombe's variant sqrt(x + 3/8)).", "Nonnegative data (counts)", "Transformed data with near-constant variance", "Order", "Additivity; original scale"),
  ...G([["D8-202", "Square transform"]],
    "Applies y = x^2 to data (for example to reduce left skew, or to energy).", "Real data", "Squared data", "Order on nonnegative values", "Sign; scale", { reading: "Generic reading as the power transform with exponent 2." }),
  ...G([["D8-016", "Box-Cox transform"]],
    "The power family y = (x^lambda - 1)/lambda (log x at lambda = 0), with lambda chosen by likelihood to make data closer to normal with stable variance.", "Positive data", "Transformed data and lambda", "Order", "Original scale; additivity"),
  ...G([["D8-166", "Quantile transform"]],
    "Maps data through its empirical distribution function and a target inverse CDF, giving uniform or normal marginals.", "Real data", "Data with a chosen marginal distribution", "Rank order", "Distances and scale"),
  ...G([["D8-055", "Feature binning transformation"]],
    "Discretizes a continuous feature into intervals (equal width, equal frequency or learned).", "Continuous feature", "Categorical or ordinal feature", "Order (for ordinal bins)", "Within-bin variation"),

  // Geometric transformations (the D4 homes that do not exist)
  ...G([["D5-072", "Inversion transformation"]],
    "Inversion in a circle or sphere: x to r^2 (x - c)/|x - c|^2. Maps generalized circles to generalized circles.", "Point set in the plane or space", "Inverted set", "Angles (conformal, orientation reversing); generalized circles", "Distances; lines (generally become circles)"),
  ...G([["D5-074", "Isometry transformation"]],
    "A distance-preserving map; in Euclidean space a composition of translation, rotation and reflection.", "Metric space", "Congruent image", "All distances and angles", "Position"),
  ...G([["D6-029", "Dilation transformation"], ["D8-188", "Scaling / Dilation transformation"]],
    "Scales about a center by a factor k: x to c + k (x - c).", "Figure or function", "Scaled figure", "Shape, angles, ratios of lengths", "Size (lengths scale by k, areas by k^2)"),
  ...G([["D6-119", "Reflection transformation"], ["D8-180", "Reflection transformation"]],
    "Reflects across a line or hyperplane: an involutive isometry reversing orientation.", "Figure", "Mirror image", "Distances, angles, size", "Orientation"),
  ...G([["D6-145", "Translation transformation"], ["D8-216", "Translation transformation"]],
    "Shifts every point by a fixed vector.", "Figure or function", "Shifted figure", "Distances, angles, orientation", "Position"),
  ...G([["D8-193", "Shearing transformation"]],
    "Moves points parallel to a fixed line by an amount proportional to their distance from it: (x, y) to (x + k y, y).", "Figure or vectors", "Sheared figure", "Area (determinant 1); parallelism; collinearity", "Angles; lengths"),
  ...G([["D8-150", "Perspective projection transformation"]],
    "Projects 3D points onto an image plane through a center: (x, y, z) to (f x / z, f y / z). A projective map.", "Points in 3D", "Points in the image plane", "Collinearity; cross-ratio", "Parallelism; distances; angles; depth"),
  ...G([["D8-145", "Orthogonal projection transformation"]],
    "Projects onto a subspace along its orthogonal complement: an idempotent self-adjoint operator P.", "Vector, subspace", "Nearest point in the subspace", "Components within the subspace; best approximation", "Orthogonal components (killed)"),
  ...G([["D5-148", "Y-Delta transform"], ["D6-158", "Y-Delta transform"], ["D8-233", "Y-\\u0394 (Wye-Delta) transformation"]],
    "Replaces a three-terminal star (Y) network by an equivalent triangle (Delta) with the same behavior at the terminals; in graph theory, a Y-Delta exchange.", "Electrical network or graph with a degree-3 vertex", "Network with a triangle replacing it", "Terminal impedances (network equivalence); planarity class", "Internal node"),
  ...G([["D8-235", "\\u0394-Y (Delta-Wye) transformation"]],
    "Replaces a triangle (Delta) with an equivalent star (Y) with a new internal node.", "Network or graph with a triangle", "Network with a star replacing it", "Terminal impedances", "Triangle edges"),

  // Matrix and tensor decompositions
  ...G([["D8-197", "Singular Value Decomposition (SVD)"]],
    "Factors any matrix A = U Sigma V* with U, V unitary and Sigma diagonal nonnegative (the singular values).", "Matrix A (m x n)", "U, Sigma, V", "Rank; operator and Frobenius norms; best low-rank approximation (Eckart-Young)", "Basis choice (singular vectors unique only up to phase and within repeated values)"),
  ...G([["D8-028", "Compact Singular Value Decomposition"]],
    "Keeps only the r nonzero singular values: A = U_r Sigma_r V_r*.", "Matrix A of rank r", "Thin factors U_r, Sigma_r, V_r", "A exactly; rank", "Null-space bases"),
  ...G([["D8-091", "Higher-Order SVD (HOSVD)"]],
    "Decomposes a tensor into a core tensor multiplied by orthogonal factor matrices, one per mode, from the SVDs of its unfoldings (De Lathauwer and coauthors).", "Order-d tensor", "Core tensor and d orthogonal matrices", "The tensor exactly; multilinear ranks", "Diagonality of the core (it is all-orthogonal, not diagonal)"),
  ...G([["D8-219", "Tucker decomposition"]],
    "Approximates a tensor as a small core multiplied by a factor matrix in each mode.", "Order-d tensor, target multilinear rank", "Core and factor matrices", "Multilinear subspace structure", "Uniqueness (rotational freedom); exactness under truncation"),
  ...G([["D8-163", "Principal Component Analysis (PCA)"]],
    "Finds orthogonal directions of maximal variance (eigenvectors of the covariance, or the SVD of centered data) and projects onto the leading ones.", "Data matrix (n samples, p features)", "Principal components and scores", "Variance captured by the kept components; Euclidean geometry of the projection", "Variance in discarded directions; non-linear structure"),
  ...G([["D8-077", "Generalized Schur (QZ) decomposition"]],
    "For a matrix pencil (A, B), finds unitary Q, Z with Q* A Z and Q* B Z upper triangular; generalized eigenvalues are ratios of diagonals.", "Matrix pair (A, B)", "Triangular pair and unitary Q, Z", "Generalized eigenvalues", "Original bases"),
  ...G([["D8-107", "Jordan decomposition"]],
    "Writes a square matrix as P J P^-1 with J block diagonal of Jordan blocks (over an algebraically closed field).", "Square matrix", "Jordan form J and change of basis P", "Similarity class; eigenvalues with algebraic and geometric multiplicities", "Numerical stability (discontinuous in the matrix)"),
  ...G([["D8-117", "LDLT factorization"]],
    "Factors a symmetric matrix as L D L^T with L unit lower triangular and D diagonal (or block diagonal with pivoting).", "Symmetric matrix", "L and D", "Inertia (Sylvester); the matrix", "Nothing; avoids square roots"),
  ...G([["D8-209", "Symbolic Cholesky decomposition"]],
    "Computes the nonzero pattern of a sparse Cholesky factor (the elimination tree and fill-in) before any numerics.", "Sparsity pattern of a symmetric positive definite matrix, ordering", "Pattern of L; elimination tree", "Structural information", "Numerical values (not computed)"),

  // Sketching, dimension reduction and numerical methods
  ...G([["D8-106", "Johnson-Lindenstrauss transform"]],
    "A random linear map to k = O(log n / epsilon^2) dimensions preserving all pairwise distances among n points within 1 +- epsilon, with high probability.", "n points in R^d", "Points in R^k", "Pairwise distances up to 1 +- epsilon", "Exact geometry; dimension"),
  ...G([["D8-171", "Random projection transformation"]],
    "Projects data by a random matrix (Gaussian, sign or sparse) to lower dimension.", "Data in R^d", "Data in R^k", "Distances and inner products approximately (JL)", "Exact geometry"),
  ...G([["D8-205", "Sub-Gaussian sketch transformation"]],
    "A sketching matrix with independent sub-Gaussian entries giving an oblivious subspace embedding.", "Matrix or vectors", "Sketched matrix S A", "Norms on a subspace up to 1 +- epsilon", "Exact values; sparsity"),
  ...G([["D8-222", "Uniform sketch transformation"]],
    "Samples rows (or columns) uniformly at random and rescales.", "Matrix A", "Row sample", "Norms approximately when coherence is low", "Guarantees under high coherence"),
  ...G([["D8-120", "LESS sketch transformation"]],
    "Leverage Score Sparsified embedding (Derezinski and coauthors): a sparse sketch whose nonzeros are placed by leverage scores, matching Gaussian sketch guarantees at lower cost.", "Tall matrix A", "Sketched matrix", "Subspace geometry approximately", "Exactness", { reading: "Recorded from memory of the randomized numerical linear algebra literature." }),
  ...G([["D8-104", "Iterative compression transformation"]],
    "Parameterized algorithm technique: build a solution for a growing instance, and at each step compress a solution of size k + 1 to size k.", "Parameterized problem instance", "Solution of size at most k or rejection", "Correctness of the parameterized decision", "Polynomial dependence on k (FPT in k)"),
  ...G([["D8-058", "Finite Difference Method (FDM) discretization"]],
    "Replaces derivatives with difference quotients on a grid, turning a differential equation into an algebraic system.", "Differential equation and grid", "Algebraic (often sparse linear) system", "Consistency; conservation for conservative schemes", "Exactness (truncation error); stability must be checked"),
  ...G([["D8-061", "Forward accumulation transformation"]],
    "Forward-mode automatic differentiation: propagates derivatives alongside values (dual numbers).", "Program computing f", "Program computing f and a directional derivative", "Exact derivative values (to rounding)", "Efficiency for many inputs (one pass per input direction)"),
  ...G([["D8-088", "Hensel lifting transformation"]],
    "Lifts a factorization or root modulo p to modulo p^k (Newton iteration p-adically).", "Polynomial with a simple root or coprime factorization modulo p", "Lifted root or factorization modulo p^k", "Factorization structure", "Nothing"),
  ...G([["D8-081", "Gr\\u00f6bner basis transformation"]],
    "Replaces a generating set of a polynomial ideal by a Groebner basis, or converts between monomial orders (FGLM, Groebner walk).", "Polynomial ideal generators, monomial order", "Groebner basis", "The ideal", "Original generators"),
  ...G([["D8-070", "Fractional programming transformation"]],
    "Turns a linear-fractional program into a linear program (Charnes-Cooper) or solves ratios by parametric search (Dinkelbach).", "Optimization of a ratio of functions", "Equivalent linear or parametric program", "Optimal solutions", "Ratio form"),
  ...G([["D8-124", "Linear programming relaxation"]],
    "Drops integrality constraints of an integer program.", "Integer program", "Linear program", "Feasible set containment; bound on the optimum", "Integrality (the relaxation gap)"),
  ...G([["D8-181", "Reformulation-Linearization Technique (RLT)"]],
    "Sherali-Adams: multiplies constraints by bound factors and linearizes products, yielding a hierarchy of tighter LP relaxations.", "Mixed integer or polynomial program", "Lifted linear program", "Validity for integer points", "Size (grows with level)"),
  ...G([["D8-111", "Laplace mechanism transformation"]],
    "Releases f(x) + Laplace(Delta f / epsilon) noise, giving epsilon-differential privacy.", "Query f with sensitivity Delta f, dataset", "Noisy answer", "Expected value; epsilon-differential privacy", "Exact answer"),
  ...G([["D8-174", "Randomized response transformation"]],
    "Each respondent answers truthfully with probability p and randomly otherwise; aggregates remain estimable.", "Individual sensitive bit", "Randomized bit", "Population frequency (estimable); local differential privacy", "Individual answer"),
  ...G([["D8-005", "Amplitude amplification transformation"]],
    "Generalized Grover iteration: rotates amplitude toward a marked subspace, boosting success probability a to near 1 in O(1/sqrt(a)) steps.", "Quantum algorithm with success amplitude sqrt(a)", "Amplified algorithm", "Unitarity; marked subspace", "Query count scales quadratically better"),
  ...G([["D8-165", "QAOA transformation"]],
    "Quantum Approximate Optimization Algorithm: alternates cost and mixer Hamiltonian evolutions with tuned angles to approximate combinatorial optima.", "Cost function on bit strings, depth p", "Parameterized quantum state and sampled solutions", "Expected cost (variationally optimized)", "Exactness (approximate)"),
  ...G([["D8-168", "Quantum Phase Estimation (QPE) transformation"]],
    "Estimates the eigenphase of a unitary on an eigenstate using controlled powers and the inverse quantum Fourier transform.", "Unitary U, eigenstate", "t-bit estimate of the phase", "Eigenstate (with high probability)", "Superposition over eigenstates collapses"),

  // Computational geometry and topology
  ...G([["D8-036", "Delaunay triangulation transform"]],
    "Triangulates a point set so no point lies inside any triangle's circumcircle; dual to the Voronoi diagram.", "Finite point set in the plane", "Delaunay triangulation", "Convex hull; maximizes the minimum angle", "Point set as unstructured"),
  ...G([["D8-227", "Voronoi diagram transformation"]],
    "Partitions space into cells of points nearest each site.", "Set of sites", "Voronoi cells", "Nearest-site structure; dual to Delaunay", "Continuous distances within cells"),
  ...G([["D8-187", "Ruppert's algorithm transformation"]],
    "Delaunay refinement: inserts circumcenters of skinny triangles and splits encroached segments to produce a quality mesh.", "Planar straight-line graph, angle bound", "Quality triangular mesh", "Input geometry; minimum angle bound", "Mesh size minimality"),
  ...G([["D8-085", "Ham-sandwich cut transformation"]],
    "Finds a hyperplane bisecting d measures in R^d simultaneously (ham sandwich theorem; algorithmic in the plane in linear time).", "d finite point sets or measures in R^d", "Bisecting hyperplane", "Halving of each measure", "Everything else about the sets"),
  ...G([["D8-226", "Vietoris-Rips complex filtration"]],
    "Builds the nested family of Vietoris-Rips complexes as the scale grows; input to persistent homology.", "Finite metric space", "Filtered simplicial complex", "Persistence diagram stable under Gromov-Hausdorff perturbation", "Exact geometry"),
  ...G([["D8-236", "\\u010cech complex filtration"]],
    "Builds the nested Cech complexes (nerves of growing balls); by the nerve theorem each has the homotopy type of the union of balls.", "Point cloud in a metric space", "Filtered simplicial complex", "Homotopy type of ball unions at each scale", "Computational economy (costlier than Rips)"),
  ...G([["D8-131", "Mapper graph transformation"]],
    "Topological data summary (Singh, Memoli and Carlsson): cover the range of a filter function, cluster each preimage, and take the nerve.", "Point cloud, filter function, cover", "Mapper graph (simplicial complex)", "Coarse shape (branches, loops)", "Fine geometry; stability depends on parameters"),
  ...G([["D8-148", "Partial persistence transformation"]],
    "Makes a data structure partially persistent: every past version can be queried, only the latest updated (Driscoll, Sarnak, Sleator and Tarjan).", "Ephemeral pointer-based data structure", "Partially persistent structure", "Query results for every version", "Nothing; amortized constant overhead for bounded in-degree"),
  ...G([["D8-142", "Node-copying transformation"]],
    "The node-copying method for persistence: copy a node when its spare pointer fields fill, keeping versions consistent.", "Pointer-based data structure", "Persistent version", "All past versions", "Space economy (copies)"),

  // Graph transformations
  ...G([["D8-047", "Dual graph transformation"]],
    "Builds the planar dual: a vertex per face, an edge crossing each edge.", "Plane graph", "Dual plane graph", "Cycles correspond to cuts; spanning trees correspond", "Embedding independence (dual depends on the embedding)"),
  ...G([["D8-134", "Medial graph transformation"]],
    "Builds a vertex per edge of a plane graph, joining edges consecutive around a face; a 4-regular plane graph.", "Plane graph", "Medial graph", "Links to the Tutte polynomial; dual has the same medial graph", "Vertex identity"),
  ...G([["D8-217", "Transpose graph transformation"]],
    "Reverses every edge of a directed graph.", "Directed graph", "Transpose graph", "Strongly connected components", "Edge direction"),
  ...G([["D8-169", "Quotient graph transformation"]],
    "Contracts each block of a vertex partition to a single vertex.", "Graph and vertex partition", "Quotient graph", "Adjacency between blocks", "Internal structure of blocks"),
  ...G([["D8-162", "Power of graph transformation"]],
    "Joins vertices at distance at most k: G^k.", "Graph G, integer k", "Graph G^k", "Vertex set; connectivity", "Distance information below k"),
  ...G([["D8-196", "Simplex graph transformation"]],
    "Builds a vertex per clique of G (including the empty clique), joining cliques differing by one vertex; a median graph.", "Graph G", "Simplex graph", "Clique structure", "Original adjacency encoding"),
  ...G([["D8-140", "Mycielskian transformation"]],
    "Builds M(G) raising the chromatic number by one while keeping the graph triangle-free.", "Graph G", "Mycielskian M(G)", "Triangle-freeness; clique number", "Chromatic number (increases by one)"),
  ...G([["D8-046", "Double graph transformation"]],
    "Builds a doubled graph: two copies of the vertex set with u' adjacent to v when u is adjacent to v (the bipartite double cover, G x K2), or the variant adding edges within copies.", "Graph G", "Doubled graph", "Degree sequence (doubled); bipartiteness for the cover", "Odd cycles (in the cover)", { reading: "Several variants in the literature; the bipartite double cover is taken as primary." }),
  ...G([["D8-080", "Graph rewriting transformation"]],
    "Replaces an occurrence of a pattern graph by another graph by a rule (double-pushout or single-pushout rewriting).", "Host graph, rule L to R, match", "Rewritten graph", "Context outside the match", "Matched subgraph"),
  ...G([["D8-199", "Source graph composition"]],
    "Unidentified as a standard named transformation.", "Unknown", "Unknown", "Unknown", "Unknown", { reading: "Could not identify this name with confidence. Fields left as Unknown rather than invented." }),

  // Complexity reductions
  ...G([["D8-160", "Polynomial-time counting reduction"]],
    "Reduces counting problem A to B in polynomial time so that the count for A is computable from counts for B (Turing or parsimonious-type counting reductions).", "Instance of counting problem A", "Instances of B and a recovery map", "Counts (hardness transfers in #P)", "Solution structure"),
  ...G([["D8-164", "PTAS reduction"]],
    "Approximation-preserving reduction: a PTAS for B yields one for A; defines APX-completeness.", "Optimization problem A instance", "Instance of B and solution map", "Approximability up to 1 + epsilon", "Exact optimum values"),

  // Series expansions
  ...G([["D7-240", "Hilbert-Poincar\\u00e9 Series Expansion"]],
    "Packages the dimensions of the graded pieces of a graded module or ring as the power series sum dim(M_n) t^n; rational for finitely generated modules over polynomial rings (Hilbert-Serre).", "Finitely generated graded module M", "Rational power series H_M(t)", "Dimension, degree and multiplicity", "Module structure beyond dimensions"),
];
